linode/apl-core

bin/validate-templates.sh

#201
You may wonder why I toggle  `pipefail` flag. 
In this particular case `grep` fails if all output lines contain `PASS` string. We haven't seen it so far, because there were always some warnings.
I also decided to not extend `otomi template` command as it would limit it's usage, i.e.: you wouldn't be able to generate a manifest just for a given file `otomi template -f <your file>`

feat: extend template validation

---

package-lock.json
values/istio-operator/istio-operator-raw.gotmpl

This fixes some bad behaviour for Istio sidecars always pulling, overloading docker registry

fix: set istio sidecar imagepullpolicy to ifnotpresent

---

Dockerfile
tools/Dockerfile

Per request @Morriz, bumped kubectl.

feat: bumped versions, both dockerfiles

---

.vscode/settings.json
values-schema.yaml

This is a format and sort -- just for consistency. Some items weren't sorted alphabetically, that kind of thing.
It would be nice to have some of these functions somewhere in an automated fashion.

fix: format & sort values-schema.yaml

---

bin/common.sh
charts/drone/templates/deployment-agent.yaml
charts/drone/templates/deployment-server.yaml
charts/drone/templates/secrets.yaml
charts/jobs/templates/configmap.yaml
charts/jobs/templates/cronjob.yaml
charts/jobs/templates/job.yaml
charts/jobs/templates/secret.yaml
helmfile.d/helmfile-30.admin.yaml
helmfile.d/helmfile-99.post.yaml
values-schema.yaml
values/drone/drone.gotmpl
values/jobs/drone.gotmpl

also injecting GCLOUD_SERVICE_KEY to avoid manual step

feat: drone job

---

bin/deploy.sh
bin/job-presync.sh
bin/otomi
helmfile.d/helmfile-99.post.yaml
helmfile.d/snippets/defaults.gotmpl
helmfile.d/snippets/job-presync.gotmpl
helmfile.d/snippets/templates.gotmpl
values/jobs/ingress-azure.gotmpl
values/jobs/test.gotmpl

Also removed `helmfile apply` and `otomi apply` to favor `sync`. This has no side effects, is faster, and only adds KBs to the payload.

Job deploy

---

.demo/env/charts/gatekeeper-operator.yaml
helmfile.d/utils/addIgnorePolicyAnnotation.gotmpl
policies/lib/annotations.rego

Forgot to add the .demo values.

fix: add demo values for gatekeeper chart

---

bin/gitea-push.sh

Push values to gitea when both local and remote are empty
#293, fixes #347
Original PR #350 had an issue where "merge with master" was not yet pushed to gitea - thus leading to a huge diff. Even after pushing "merge with master" to gitea branch, it would not upload, needed to close & create new PR. Sorry.

Gitea post deploy

---

bin/common.sh
bin/gen-drone.sh
bin/otomi

feat: docker pull before run

---

bin/gen-drone.sh

Fixes bug that was introduced by the docker pull before run issue.
#370 #382 #394

fix: fixes bug introduced by #370 / #382

---

bin/common.sh
bin/otomi

#382 broke an execution path I rely on for my own Docker image.
I also saw `$has_docker` two times, curious why that's necessary?

bin/otomi and bin/common.sh conditionals

---

values-schema.yaml

fix: add loadBalancerRG to nginx-ingeress in values-schema.yaml

fix: add loadBalancerRG to nginx-ingeress in values-schema.yaml

---

values-schema.yaml

fix for [otomi-api #182](https://github.com/redkubes/otomi-api/issues/182)

set maxlength of dns

---

README.md

Reverting the readme file to the latest good state.

fix: reverting back the readme file.

---

bin/common.sh

its better to get otomi version from settings file, where otomi value is already defined

[skip-ci] fix for otomi version setting

---

bin/common.sh
bin/otomi

Linux workaround

---

values/otomi-console/otomi-console.gotmpl

Closes https://github.com/redkubes/unassigned-issues/issues/242.

Team services in CE mode enhancement

---

src/cmd/commit.ts

Pushing to gitea

---

values-schema.yaml

Some of the secret generation functions changed based on the requirements of the charts

fix: changes some secrets requirements.

---

src/cmd/commit.ts

fix: await for file generation

---

src/server/index.ts

makes sure the api commit also runs genDrone

fix: gen-drone added to request to encrypt for now

---

tests/fixtures/env/teams/jobs.demo.yaml
values-schema.yaml

Make schema robust

---

helmfile.d/snippets/sops-env.gotmpl

fix: missing quotes around templated object

---

.github/workflows/main.yml
.gitignore
README.md
chart/otomi/Chart.yaml
values-schema.yaml

including small schema fix for slack defaults

build(readme): readme now inserted into chart with values.md appended

---

core.yaml
helmfile.d/snippets/defaults.yaml
values-schema.yaml
values/gatekeeper/gatekeeper-operator.gotmpl

also moved the defaults
fixes redkubes/unassigned-issues#345

refactor(gatekeeper): gatekeeper now by default nonblocking

---

src/cmd/commit.ts

https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/redkubes/unassigned-issues/346
Providing command for accessing password is still problematic - I am still working on it

feat: add final message

---

.github/pull_request_template.md

We also need to install app to enforce validation of checklist: https://github.com/marketplace/task-list-completed

chore: add PR checklist

---

src/cmd/bootstrap.ts

fix: overwrite with input values

---

README.md

- Ran Grammarly on the README.md

fix: grammar check on README.md 

---

.eslintrc.yml
.vscode/launch.json
Dockerfile
chart/otomi/templates/job.yaml
helmfile.d/snippets/job.gotmpl
src/cmd/apply.ts
src/cmd/bootstrap.test.ts
src/cmd/bootstrap.ts
src/cmd/commit.ts
src/common/k8s.ts
src/common/values.ts
values/cert-manager/cert-manager-raw.gotmpl
values/jobs/gitea-prepare.gotmpl
values/jobs/keycloak.gotmpl
values/kubernetes-external-secrets/kubernetes-external-secrets.gotmpl
values/otomi-api/otomi-api.gotmpl
values/otomi-console/otomi-console.gotmpl
values/vault-operator/vault-operator-raw.gotmpl
versions.yaml

fixes multiple issues:
- merging of chart values now correct with lodash' `merge`
- wait-for init containers removed from tasks as they already do dns retries

fix: wait for, chart value merge issues, clusterissuer

---

helmfile.d/snippets/job.gotmpl

fix: export env

---

charts/gatekeeper-operator/templates/post-job.yaml

fix: gatekeeper postinstall job securityContext

---

package-lock.json
src/cmd/bootstrap.ts

fixes master...this PR should replace #692

fix: bootstrap should only validate only input values [kind]

---

README.md

feat: updated community section

---

charts/kured/Chart.yaml
charts/kured/README.md
charts/kured/ci/prometheus-values.yaml
charts/kured/templates/clusterrole.yaml
charts/kured/templates/daemonset.yaml
charts/kured/templates/service.yaml
charts/kured/values.minikube.yaml
charts/kured/values.yaml
values/kured/kured.gotmpl

- feat: #748
- lowered resources request+limit

feat(kured): feat: #748

---

versions.yaml

feat: bump api and console versions

---

policies/psp-host-networking-ports/src.rego
policies/psp-host-security/src.rego
policies/psp-privileged/src.rego

fix policies:
- psp-priviliged
- psp-host-networking 
- psp-host-security

fix(gatekeeper): several policies

---

.cspell.json
.values/env/teams/external-secrets.admin.yaml
.values/env/teams/jobs.admin.yaml
.values/env/teams/services.admin.yaml
chart/otomi/values-localhost.yaml
chart/otomi/values.yaml
charts/team-ns/templates/external-secrets.yaml
charts/team-ns/templates/knative-services.yaml
helmfile.d/helmfile-15.ingress-core.yaml
helmfile.d/helmfile-60.teams.yaml
helmfile.d/snippets/domains.gotmpl
helmfile.d/snippets/env.gotmpl
values-schema.yaml
values/keycloak/keycloak.gotmpl
values/kubeapps/kubeapps.gotmpl
versions.yaml

Allows admins to create services and jobs, in the namespace of their choice, to accomodate exposure of own platform tooling.

feat: admin services

---

.github/pull_request_template.md
helmfile.d/helmfile-00.uninstall.yaml
helmfile.tpl/helmfile-00.uninstall.yaml
helmfile.tpl/helmfile-pre-upgrade-to-v0.16.yaml
upgrades.yaml

Upgrade to 16

---

helmfile.d/helmfile-21.wait.yaml
helmfile.d/helmfile-60.teams.yaml
helmfile.d/snippets/env.gotmpl
versions.yaml

Upgrade api and console and fix minor issues

---

charts/team-ns/templates/networkpolicy.yaml
helmfile.d/helmfile-60.teams.yaml
helmfile.d/snippets/alertmanager/opsgenie.gotmpl

fix(alerting): fixes issues in #797

---

values/knative/knative-serving-cr.gotmpl
values/knative/knative-serving-raw.gotmpl

fixes redkubes/unassigned-issues#414

fix: knative versioning, istio peerauthentication with defaults removed

---

README.md

docs(readme.md): added referral link to DO marketplace

---

tpl/.drone.yml.gotmpl
values/knative/knative-serving-cr.gotmpl
versions.yaml

fix: drone now running bootstrap instead of migrate before apply

---

.values/env/teams.yaml
charts/kubernetes-external-secrets/Chart.yaml
charts/kubernetes-external-secrets/README.md
charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml
charts/kubernetes-external-secrets/templates/deployment.yaml
charts/kubernetes-external-secrets/templates/pdb.yaml
charts/kubernetes-external-secrets/templates/rbac.yaml
charts/kubernetes-external-secrets/values.yaml
charts/team-ns/templates/external-secrets.yaml
core.yaml
helmfile.d/helmfile-06.init.yaml
helmfile.d/helmfile-15.ingress-core.yaml
helmfile.d/snippets/defaults.yaml
src/cmd/destroy.ts
src/cmd/playground.ts
src/cmd/pre-upgrade.ts
src/cmd/sync.ts
src/common/utils.ts
tests/fixtures/env/apps/kubernetes-external-secrets.yaml
tests/fixtures/env/teams.yaml
tests/kind/env/teams.yaml
upgrades.yaml
values-schema.yaml
values/drone/drone.gotmpl
values/external-secrets/external-secrets.gotmpl
values/kubernetes-external-secrets/kubernetes-external-secrets.gotmpl
values/vault-operator/vault-operator-raw.gotmpl
versions.yaml

fix: external secrets regression, missing team-admin values

---

.github/workflows/integration.yml
tests/integration/full.yaml
tests/integration/minimal.yaml

test: k8sversion placeholder

---

.github/workflows/integration.yml
.github/workflows/main.yml

implement redkubes/unassigned-issues#433

ci: integration tests strategy parameters 

---

CHANGELOG.md
package-lock.json
package.json

This is a test if releases can by merging PR

chore(release): 0.16.12

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 0.16.13

---

.cspell.json
README.md
values-schema.yaml
values/drone/drone.gotmpl
values/gitea/gitea.gotmpl
values/harbor/harbor.gotmpl
values/keycloak/keycloak.gotmpl
values/oauth2-proxy/oauth2-proxy-redis.gotmpl

This PR adds a new cluster.provider to Otomi for Vultr managed kubernetes.
The VKE requires minimal persistent volumes size of 10GB

feat: add vultr provider

---

.cspell.json
README.md
core.yaml

Descriptions of apps in Console now in core.yaml in otomi-core.

feat: app descriptions in core

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 0.16.14

---

.github/workflows/integration-on-schedule.yml
tests/integration/minimal.yaml

test: scheduled integration test with minimal input values

---

.gitattributes
helmfile.d/snippets/blackbox-targets.gotmpl
tests/fixtures/env/secrets.teams.yaml
tests/fixtures/env/teams.yaml
tests/fixtures/env/teams/services.demo.yaml

test: fixtures cleanup

---

.github/workflows/integration.yml

feat: integration tests with unique cluster names

---

.github/workflows/integration-on-schedule-full.yml

test: remove duplicated tests

---

tests/fixtures/env/apps/gitea.yaml
tests/fixtures/env/apps/grafana.yaml
tests/fixtures/env/apps/loki.yaml
tests/fixtures/env/apps/secrets.loki.yaml
tests/fixtures/env/settings.yaml
tests/fixtures/env/teams.yaml
tests/fixtures/env/teams/services.demo.yaml
tests/kind/env/apps/grafana.yaml
tests/kind/env/settings.yaml
values-changes.yaml
values-schema.yaml
values/loki/loki.gotmpl

Depends on:  https://github.com/redkubes/otomi-api/pull/330

fix: loki storage config

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 0.16.15

---

versions.yaml

chore: versions

---

.github/workflows/integration-on-schedule-full.yml
.github/workflows/integration-on-schedule-minimal.yml
.github/workflows/integration.yml
tests/integration/full.yaml
versions.yaml

fix: integration tests

---

CHANGELOG.md
package-lock.json
package.json
versions.yaml

chore(release): 0.16.17

---

.github/workflows/integration.yml

test: add  workflow dispatch options and fix scheduled workflow

---

.github/workflows/integration.yml

The required condition is not needed as there are default values.

test: remove required fields as there are defaults

---

.github/workflows/integration.yml

test: fix broken GitHub pipeline expression

---

.github/workflows/integration.yml

test: increase workflow timeout

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 0.16.19

---

src/cmd/validate-templates.ts

I know that some of you were struggling to find out the issue when validate-templates was failing, because the output was way too promiscuous - around 800 lines. It is happening in both CI pipeline and Drone pipeline.
This PR aims to significantly decrease the amount of information printed out. In particularly it will not print out information about each file that has passed the validation. The warning and error about each file is still printed out.
Now the validation output look like below:

feat: less promiscuous validate-template output

---

.github/workflows/integration.yml
tests/integration/full.yaml

test: add minio to test scenario [ci skip]

---

CHANGELOG.md
package-lock.json
package.json
versions.yaml

chore(release): 0.16.21

---

CHANGELOG.md
package-lock.json
package.json
versions.yaml

chore(release): 0.17.1

---

src/cmd/apply.ts
src/cmd/upgrade.ts
upgrades.yaml

fix: olm upgrade

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 0.18.1

---

values-schema.yaml

fix: required property for egress policy

---

.github/workflows/integration-on-schedule-dns.yml
.github/workflows/integration-on-schedule-full.yml
.github/workflows/integration-on-schedule-minimal.yml
.github/workflows/integration.yml

test: update k8s versions for ci setup [ci skip]

---

tests/integration/minimal-with-team.yaml

test: add httpbin as test app

---

upgrades.yaml
upgrades/pre/upgrade-0-18-1.sh

feat: move upgrade script to a separate file

---

.values/env/settings.yaml
.values/env/teams/apps.admin.yaml
.values/env/teams/external-secrets.admin.yaml
.values/env/teams/jobs.admin.yaml
.values/env/teams/services.admin.yaml
.values/env/teams/workloads.admin.yaml
charts/host-mods/scripts/setup.sh
helmfile.d/snippets/defaults.yaml
src/cmd/pull.ts
src/common/bootstrap.ts
tests/fixtures/env/settings.yaml
tests/kind/env/settings.yaml
tests/kind/env/teams/workloads.admin.yaml
tests/kind/env/teams/workloads.demo.yaml
values-changes.yaml
values-schema.yaml
versions.yaml

- Fix Harbour S3 Backend storage
- Fix `otomi pull and otomi commit` (by [Maurice](https://github.com/Morriz))

fix: Harbour S3 storage and otomi pull/commit

---

README.md

fix: helm command in doc

---

values/thanos/thanos.gotmpl

This PR fixes the S3 configuration for Thanos objstore

fix: Thanos s3 objstore cfg

---

charts/argocd-operator/templates/catalog_source.yaml

fix: argocd operator

---

versions.yaml

chore: set versions

---

package.json

chore: print all app versions

---

values-schema.yaml
versions.yaml

https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/gh/redkubes/unassigned-issues/574
This PR adds fields to the `values-schema.yaml` file for team projects feature.
Is paired with: https://github.com/redkubes/otomi-api/pull/406 and https://github.com/redkubes/otomi-console/pull/289
Added `projects` and `project` fields to the `values-schema.yaml` file.

feat: team projects

---

charts/kured/Chart.yaml
charts/kured/README.md
charts/kured/templates/NOTES.txt
charts/kured/templates/_helpers.tpl
charts/kured/templates/daemonset.yaml
charts/kured/values.minikube.yaml
charts/kured/values.yaml
upgrades.yaml
upgrades/pre/upgrade-0-22-0.sh
values/kured/kured.gotmpl

Upgrade Kured to version 4.6.0

feat: upgrade kured

---

charts/team-ns/templates/istio-virtualservices.yaml
tests/fixtures/env/teams/services.demo.yaml
values-schema.yaml

add custom request headers to istio virtual services

feat: add custom request headers

---

tests/integration/full.yaml

test: enable thanos

---

helmfile.d/snippets/alertmanager.gotmpl
helmfile.d/snippets/defaults.yaml
tests/fixtures/env/settings.yaml
values-schema.yaml
versions.yaml

Set null receiver as default for alertmanagers if no other receivers are used

fix: configure null receiver for alertmanager

---

charts/jaeger-operator/COMPATIBILITY.md
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/crds/crd.yaml
charts/jaeger-operator/templates/NOTES.txt
charts/jaeger-operator/templates/certificate.yaml
charts/jaeger-operator/templates/crds.yaml
charts/jaeger-operator/templates/deployment.yaml
charts/jaeger-operator/templates/issuer.yaml
charts/jaeger-operator/templates/mutating-webhook.yaml
charts/jaeger-operator/templates/role.yaml
charts/jaeger-operator/templates/service-account.yaml
charts/jaeger-operator/templates/service.yaml
charts/jaeger-operator/templates/validating-webhook.yaml
charts/jaeger-operator/values.yaml

Updated jaeger operator chart so it supports k8s version 1.25.

feat: updating jaeger-operator

---

helmfile.d/snippets/defaults.yaml

Applying lessons learned from client deployments to the defaults

fix: Loki distr. defaults tweaks

---

tools/Dockerfile-tty

feat: added helm to the tty console

---

.github/workflows/integration.yml

This PR adds a poolname for scaleway and makes DigitalOcean the default cloud provider.

fix: scaleway setting

---

.github/workflows/integration.yml
src/common/values.ts
tests/bootstrap/input.yaml

This PR aims to improve development workflow, so DEVs do not need to register dev cluster in otomi cloud

test: inject license

---

charts/team-ns/templates/isitio-tty-authn.yaml
versions.yaml

feat: add authorization to the tty console

---

.github/workflows/integration.yml

This PR fixes workflows by changing back the spelling of kubernetes_versions.

fix: changes spelling

---

.github/workflows/integration-on-schedule-dns-no-admin-pass.yml
.github/workflows/integration-on-schedule-dns.yml
.github/workflows/integration-on-schedule-full.yml
.github/workflows/integration-on-schedule-minimal-no-admin-pass.yml
.github/workflows/integration-on-schedule-minimal-with-team.yml
.github/workflows/integration-on-schedule-minimal.yml
.github/workflows/integration.yml

This PR removes the cluster_region from the yaml files because it isn't used anymore.

fix: workflow remove cluster regions

---

.github/workflows/integration.yml

This MR updates the name of the cluster that will be created for better readability.

feat: updating cluster name

---

.github/workflows/integration.yml

This PR changes the default cloud provider to be scaleway again.

fix: scaleway default cloud provider

---

.github/workflows/integration-on-schedule-dns-no-admin-pass.yml
.github/workflows/integration-on-schedule-dns.yml
.github/workflows/integration-on-schedule-full.yml
.github/workflows/integration-on-schedule-minimal-no-admin-pass.yml
.github/workflows/integration-on-schedule-minimal-with-team.yml
.github/workflows/integration-on-schedule-minimal.yml

This PR changes the cron times to check if the schedules jobs are fixed

fix: cron times changed for testing purposes

---

.github/workflows/integration-on-schedule-dns-no-admin-pass.yml

This PR changes back the scheduled job time to be run at midnight.

fix: change back scheduled job time

---

charts/prometheus-msteams/templates/deployment.yaml
helmfile.d/helmfile-10.monitoring.yaml
helmfile.d/snippets/alertmanager.gotmpl
tests/fixtures/env/settings.yaml
values/prometheus-msteams/prometheus-msteams.gotmpl

Fixes multiple configuration issues when using msteams as reciever for alertmanager

fix: msteams receivers

---

.values/env/settings.yaml
helmfile.d/helmfile-04.databases.yaml
helmfile.d/helmfile-09.init.yaml
helmfile.d/snippets/defaults.yaml
package.json
tests/fixtures/env/settings.yaml
upgrades.yaml
upgrades/pre/upgrade-0-23-0.sh
upgrades/pre/upgrade-0-25-0.sh
values/keycloak/keycloak.gotmpl

This PR ensures that databases is in place before core apps are trying to use it.
In addition a script is modified to support upgrade of the upcoming version

feat: initialise databases at the very beginning

---

.github/workflows/integration.yml
values/jobs/drone-activation.gotmpl

This PR solves the issue with Pods being evicted due to ephemeral storage pressure issue on Scaleway.

test: increase scw disk size

---

.github/workflows/main.yml

This MR adds the docker commands to push to ghcr when a release branch is pushed

feat: push release image to ghcr.io

---

.github/workflows/main.yml

This MR will fix the image tag when pushing the release version to ghcr.io

fix: updated image tag for ghcr

---

.github/workflows/main.yml
.github/workflows/scw-remove-clusters-dev-on-schedule.yml

This PR makes it so that clusters on Scaleway are automatically deleted after 19:00 in the dev projects
User Story: [665](https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/gh/redkubes/unassigned-issues/665)

feat: scw auto remove clusters on dev

---

tests/integration/full.yaml

The `full` test case scenario should enable all apps.

test: enable more apps

---

charts/grafana-dashboards/velero/velero.json

fixes #1278 
Fixes legacy datasource query in grafana dashboard for Velero

fix: upgrade legacy datasource query

---

tools/Dockerfile

chore: update helm and kubectl [TOOLS][MINOR]

---

charts/team-ns/templates/argocd/argocd-applicationset.yaml
tests/fixtures/env/teams/workloads.demo.yaml

The strategy in the annotations for auto image update where not correct and a '-' in one of the aliasses was missing. This PR solves it.

fix: update strategy in appset

---

chart/otomi/templates/job.yaml
chart/otomi/templates/post-job.yaml

fixes #1316
tested installation with https://github.com/redkubes/otomi-core/actions/runs/6505454514/job/17669110478
and deletion with: `helm uninstall otomi`

feat: enhnace Otomi job security context

---

.github/workflows/integration.yml

This PR fixes the deployment on scaleway.

fix: scaleway deploy

---

.github/workflows/scw-remove-clusters-dev-on-schedule.yml

This MR fixes the scheduled cleanup of the private networks in scaleway.

fix: scheduled scw private networks cleanup

---

README.md

fix: add promo to readme

---

.github/workflows/integration.yml

This MR fixes an issue in the current integration workflow which breaks the otomi deployment from main branch.

ci: fixing integration workflow

---

apps.yaml

Update versions and titles of multiple apps.

fix: app versions in apps.yaml

---

charts/team-ns/templates/argocd/argocd-applicationset.yaml
tests/fixtures/env/teams/workloads.demo.yaml
values-schema.yaml
versions.yaml

Changes in schema and applicationset template

fix: auto update schema

---

charts/team-ns/templates/rbac.yaml

Remove tekton enabled deb for creating tekton rbac in team namespace

fix: rm tekton enabled flags

---

README.md

fix: update readme for v2

---

.github/workflows/main.yml

fix: releasing helm chart

---

charts/otomi-pipelines/templates/tekton-otomi-task.yaml

fix: tekton task path

---

.github/workflows/main.yml

This MR fixes helm chart version

ci: fix chart version on release

---

charts/grafana-dashboards/k8s-admin/pvc.json

Adds the default pvc dashboard to the platform Grafana

fix: add pvc dashboard to platform grafana

---

charts/team-ns/templates/_helpers.tpl
charts/team-ns/templates/networkpolicy.yaml

Configure selector labels for service monitors

fix: set prom netpol selector

---

values/prometheus-operator/prometheus-operator.gotmpl
versions.yaml

required grafana ini settings for Otomi console dashboards

fix: grafana settings

---

charts/team-ns/templates/builds/docker.yaml
tests/fixtures/env/teams/builds.demo.yaml

Set context for Docker build in case of dockerfile in a nested directory structure

fix: docker build context

---

.github/workflows/slackbot-release.yml

This PR adds a workflow that creates a message to the otomi announcements slack channel

feat: slack release

---

charts/team-ns/templates/builds/docker.yaml
tests/fixtures/env/teams/builds.demo.yaml
values-schema.yaml

Add option to add environment variables to use during build-time

fix: kaniko env

---

apps.yaml
charts/keycloak-operator/Chart.yaml
charts/keycloak-operator/templates/deployment.yaml
values/keycloak-operator/keycloak-operator-cr.gotmpl
values/keycloak-operator/keycloak-operator.gotmpl

fixes redkubes/unassigned-issues#752
Test cases:

feat: upgrade keycloak to 22.0.4

---

helmfile.d/snippets/derived.gotmpl
values-schema.yaml

fix: linode provider

---

charts/cert-manager-webhook-linode/templates/deployment.yaml
charts/cert-manager-webhook-linode/values.yaml
values/cert-manager-webhook-linode/cert-manager-webhook-linode.gotmpl

fix: linode webhook

---

helmfile.d/helmfile-21.wait.yaml
values/jobs/keycloak.gotmpl
versions.yaml

partially-fixes #1474
By increasing retries to 100, we increase waiting time up to 30 minutes for DNS records

feat: increase wait time for keycloak

---

chart/otomi/Chart.yaml
helmfile.d/snippets/derived.gotmpl

Set extra args for metrics-server if provider is linode

fix: set tls for metrics-server

---

values/prometheus-operator/prometheus-operator.gotmpl

This PR aims to fix Tempo and Loki deps

fix: tempo manifests that depends on loki

---

chart/otomi/templates/job.yaml
charts/gitea/templates/gitea/statefulset.yaml
charts/gitea/values.yaml
charts/jobs/templates/_helpers.tpl
charts/jobs/values.yaml
charts/wait-for/templates/job.yaml
charts/wait-for/values.yaml
helmfile.d/helmfile-21.wait.yaml
helmfile.d/snippets/job.gotmpl
src/cmd/apply.ts
values/gitea/gitea.gotmpl
values/jobs/keycloak.gotmpl

implements #1481
depends-on redkubes/otomi-tasks#98

feat: set pod dns for jobs

---

.github/workflows/integration.yml

Adds new scenario do deploy just a cluster.

ci: deploy scaleway cluster

---

apps.yaml
values-schema.yaml
versions.yaml

This PR fixes:
- isBeta: true
- default enabled: false

fix: added is beta disabled app

---

charts/grafana-dashboards/k8s-admin/compute-cluster.json

This reverts commit 9323a9714a83dc78d88802a30f5e986ccfd606a6.

fix: mem util dashboard (#1526)

---

upgrades/pre/upgrade-2-7-0.sh

This MR fixes the upgrade script for v2.7.0

fix: updated upgrade script

---

tools/Dockerfile-tty

This MR updates the velero binaries in the tty shell to match the velero server version(v1.13)

feat: update velero cli

---

bin/install-deps.sh
docs/development.md
package.json

For local development  otomi cli needs few binaries.

chore: install dependencies

---

.github/workflows/otomi-tools-build-push.yaml

fix: add missing if check in otomi tools image build

---

charts/otomi-pipelines/templates/tekton-otomi-task-teams.yaml
charts/otomi-pipelines/templates/tekton-otomi-task.yaml

This PR prepares Otomi-pipeline to upgrade to Otomi v3
After this PR is merged we will make patch release v2.11.5
The tested upgrade path
v2.11.4 =>  v2.11.5-rc-1 => main

feat: prepare otomi pipeline for upgrade to v3

---

core.yaml
src/cmd/commit.ts

feat: console prefix

---

charts/gitea/templates/gitea/statefulset.yaml
charts/harbor/templates/redis/statefulset.yaml
charts/harbor/templates/trivy/trivy-sts.yaml
charts/oauth2-proxy/charts/redis/templates/master/application.yaml
charts/oauth2-proxy/charts/redis/templates/replicas/statefulset.yaml
charts/oauth2-proxy/charts/redis/templates/sentinel/statefulset.yaml
charts/otomi-pipelines/templates/eventlistener.yaml
charts/otomi-pipelines/templates/tekton-otomi-git-clone.yaml
charts/otomi-pipelines/templates/tekton-otomi-task-teams.yaml
charts/otomi-pipelines/templates/tekton-otomi-task.yaml
charts/otomi-pipelines/templates/tekton-pipeline.yaml
charts/tempo/templates/lib/service-monitor.tpl
src/cmd/apply-as-apps.ts
src/cmd/apply.ts
values/argocd/argocd.gotmpl
values/jaeger-operator/jaeger-operator.gotmpl

feat: deploy core apps via argocd

---

helmfile.d/snippets/defaults.yaml
tests/fixtures/env/apps/argocd.yaml
values-schema.yaml
values/argocd/argocd-raw.gotmpl
values/argocd/argocd.gotmpl

ArgoCD defaults for new defaults approach

fix: argocd defaults

---

package.json
tests/bootstrap/input.yaml

This change ensures we test values bootstrap functionality on every docker build or git push.

test: bootstrap values as part of test suite

---

values/gitea/gitea-otomi-db.gotmpl
values/keycloak/keycloak-otomi-db.gotmpl

location is now inline with the harbor database which is working.

fix: cnpg linode obj location for gitea and keycloak

---

versions.yaml

fix: versions.yaml

---

tests/integration/full.yaml

This PR disables Velero for the full installation profile.

feat: disable velero for full install profile

---

charts/otomi-pipelines/templates/tekton-otomi-git-clone.yaml
charts/otomi-pipelines/templates/tekton-otomi-task-teams.yaml
charts/otomi-pipelines/templates/tekton-otomi-task.yaml

fix: git protocol

---

apps.yaml
helmfile.d/snippets/alertmanager.gotmpl
helmfile.d/snippets/defaults.yaml
tests/fixtures/env/secrets.settings.yaml
tests/fixtures/env/settings.yaml
values-changes.yaml
values-schema.yaml

Remove home notifications, also known as co-monitoring.

fix: rm home alerts

---

versions.yaml

https://github.com/linode/apl-tasks/releases/tag/v3.1.0

chore: apl-tasks version

---

charts/team-ns/templates/backup/schedule.yaml

Changing the locations in the schedule template to match configured locations in Velero

fix: locations in schedule

---

.github/workflows/otomi-tools-build-push.yaml
versions.yaml

This PR updates the `versions.yaml` file.

fix: versions

---

versions.yaml

Set api and console versions to main

fix: set versions to main

---

chart/apl/templates/NOTES.txt

adjust helm chart notes to new naming and docs url

fix: helm notes

---

.cspell.json
helmfile.d/snippets/defaults.yaml
values-changes.yaml
values-schema.yaml
values/cert-manager/cert-manager.gotmpl

Improve resource configuration for the following apps:
- cert-manager (including removing hard coded resource configuration in `.gotmpl`
- tempo
- falco (exporter)
- jaeger
- api-tools

fix: resource defaults

---

src/cmd/bootstrap.test.ts
src/cmd/bootstrap.ts

This PR fixes the getting of kms values and corrects the order of Age key generation, preventing the creation of multiple Age keys.

fix: get kms values & age key generation order

---

values/keycloak-operator/keycloak-operator-cr.gotmpl
versions.yaml

(cherry picked from commit eef0dcb03aec735f1ce1c8885159a35881586190)

fix: keycloak login page tag

---

Dockerfile

The sequel of: https://github.com/linode/apl-core/pull/1788

feat: update tools version

---

src/common/envalid.ts

Adjust the retry mechanism to 1 minute of 30 retries

feat: adjust retry factor to 1 and 30 retries of 1 minute

---

charts/grafana-dashboards/falco-teams/falco-teams.json
charts/grafana-dashboards/trivy-teams/trivy-teams.json

Add datasource var to Team Grafana Falco dashboard

fix: falco team grafana falco dashboard datasource

---

versions.yaml

chore(): update api v3.4.0

---

core.yaml
versions.yaml

- added path for gitea
Is related to:
- https://github.com/linode/apl-api/pull/601
- https://github.com/linode/apl-console/pull/482

feat: add path for gitea

---

tests/bootstrap/input.yaml
tests/fixtures/env/teams/builds.demo.yaml
tests/integration/minimal-with-team.yaml
tests/integration/upgrade.yaml

Fixing some broken builds that existed in the inputs.yaml.

fix: broken builds in the input files

---

src/common/k8s.test.ts
src/common/k8s.ts

- Fix the check to compare argocd resources for the application-controller.

fix: resource check for argocd controller

---

versions.yaml

This PR updates the apl-console version to the new patch release 3.4.2

fix: update message

---

helmfile.d/snippets/defaults.yaml

This PR fixes the default cpu resources for the platform databases. This will allow new APL installations to use less cpu for system DBs. The values-changes.yaml will tak care on migrating existing databases resources to the new values.

feat: lowering DBs cpu resources

---

helmfile.d/snippets/defaults.gotmpl
helmfile.d/snippets/defaults.yaml

See [APL-476](https://jira.linode.com/browse/APL-467) for full context.
How to test:
- Deploy AAP using this branch or update existing AAP to this branch
- Create a team using the values repo (`env/teams.yaml`) by adding only the new team block containing a value for `id` and `password` (random value) e.g.
```
teamConfig:
demo:
id: demo
password:
```
- Add a team user via the console
- Login as the new team user and create a workload
- After the workload is deployed try creating a service that exposes it. If it works the test is successful.
- Previously you would encounter a greyed out "Exposure (ingress)" form like this

feat: Apl-476 updating teams defaults

---

core.yaml
values/gitea/gitea.gotmpl

- As a workaround for bug: https://github.com/go-gitea/gitea/issues/17740 in Gitea. We can set a very low session time so that the login issue will not appear.

fix: update session settings for Gitea

---

src/common/crypt.ts

fix: encryption

---

helmfile.d/snippets/defaults.gotmpl
helmfile.d/snippets/derived.gotmpl
src/cmd/apply.ts
src/cmd/commit.ts
src/common/bootstrap.ts
src/common/values.ts
values-schema.yaml

Reintroduces #1910, with a fix for the consequence of Git restarting.

fix: unique admin password for gitea

---

tests/fixtures/env/teams/dev/sealedsecrets/42c53642-3b02-4d64-9a15-256d233b7bd2.yaml
tests/fixtures/env/teams/dev/sealedsecrets/a916fd8f-f7d7-4621-908a-6f0cc38dd24b.yaml
tests/fixtures/env/teams/sealedsecrets.admin.yaml
tests/fixtures/env/teams/sealedsecrets.demo.yaml
tests/fixtures/env/teams/sealedsecrets.dev.yaml
upgrades.yaml
upgrades/pre/upgrade-4-4-0.mjs
values-changes.yaml

This PR adds an upgrade script, performing a secrets migration according to changes made in #1924 .

feat: added upgrade script for secrets

---

versions.yaml

feat: update versions.yaml

---

charts/team-ns/templates/argocd/argocd-applicationset.yaml

A few additional `ignoreDifferences` for applications created by team-admin.
These additions are required for APL-556

fix: ignoreDifferences for apps created by team-admin

---

values/otomi-api/otomi-api.gotmpl

Ticket: https://jira.linode.com/browse/APL-680

fix: user cluster url for gitea in api

---

.env.sample
src/cmd/bootstrap.ts
src/cmd/validate-values.ts
src/common/crypt.ts
src/server.ts

- Add option for request to prepare values to add files that only needs to be encrypted or decrypted
- Fixed issue where we CD into directories which resulted in race conditions in other processes

fix: 5xx errors

---

versions.yaml

chore: update api version

---

tests/fixtures/env/apps/otomi-api.yaml
values/otomi-api/otomi-api.gotmpl

We still need public url in order to connect easily local env to existing cluster

feat: add gitea repo public url as env

---

versions.yaml

chore: update versions

---

charts/team-ns/templates/builds/buildpack.yaml
charts/team-ns/templates/builds/docker.yaml
tests/fixtures/env/teams/demo/builds/demo-ext-repo-buildpacks-public-trigger.yaml
tests/fixtures/env/teams/demo/builds/demo-ext-repo-private-trigger.yaml
tests/fixtures/env/teams/demo/builds/demo-ext-repo-private.yaml
tests/fixtures/env/teams/demo/builds/demo-ext-repo-public-trigger.yaml
tests/fixtures/env/teams/demo/builds/demo-ext-repo-public.yaml

fix: render build git-credentials only if secretName specified

---

src/cmd/validate-values.ts

fix: log complete error of ajv validation

---

src/cmd/commit.ts

fix: commit and push

---

helmfile.d/snippets/defaults.yaml
values-changes.yaml

fix: correct values order

---

values/argocd/argocd.gotmpl

See docs: https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cm-yaml/

feat: argocd to check repo every 15s

---

src/cmd/migrate.ts

This provides an immediate fix for a double-encryption on values after the migration.
Steps to test:
* Deploy cluster on current release.
* Upgrade to main branch.

fix: decrypt after updated structure encryption

---

src/common/crypt.ts

fix: only encrypt secret files if not encrypted

---

.github/workflows/create_rc.yml
.github/workflows/patch_rc.yml

ci: using node 20

---

.github/workflows/create_rc.yml
.github/workflows/patch_rc.yml

Minor change to use BOT_EMAIL and BOT_USERNAME repo variables.

ci: using BOT_EMAIL and BOT_USERNAME variables

---

CODEOWNERS
helmfile.d/snippets/defaults.gotmpl

fix: set team defaults

---

helmfile.d/snippets/defaults.gotmpl

fix: selfservice defaults

---

charts/otomi-pipelines/templates/tekton-pipeline.yaml

fix: dont run team-tasks on "ci_skip" commits

---

charts/apl-gitea-operator/templates/rbac.yaml

feat: allow gitea-operator to list pods in Gitea namespace

---

src/cmd/bootstrap.ts
src/common/utils.test.ts
src/common/utils.ts

fix: ensure sealedsecrets and workloadValues directories exist

---

charts/team-ns/templates/builds/buildpack.yaml
charts/team-ns/templates/builds/docker.yaml
charts/team-ns/templates/tekton-tasks/buildpacks.yaml
charts/team-ns/templates/tekton-tasks/git-clone.yaml
charts/team-ns/templates/tekton-tasks/grype.yaml
charts/team-ns/templates/tekton-tasks/kaniko.yaml

Ensures the order of resources to prevent the CouldntGetPipeline error.
Annotation for the individual resources guarantees that the essential Tekton components are deployed before higher level abstractions.

feat: add argocd sync waves to ensure tasks and pipelines are created in the right order

---

charts/drone/templates/_provider-envs.tpl
charts/otomi-pipelines/templates/secret.yaml
charts/team-ns/templates/argocd/argocd-repo-secret.yaml
helmfile.d/snippets/alertmanager-teams.gotmpl
helmfile.d/snippets/alertmanager.gotmpl
helmfile.d/snippets/derived.gotmpl
helmfile.d/snippets/grafana.gotmpl
values/argocd/argocd.gotmpl
values/cert-manager/cert-manager.gotmpl
values/drone/drone-admit-members.gotmpl
values/drone/drone.gotmpl
values/gitea/gitea.gotmpl
values/harbor/harbor.gotmpl
values/jobs/drone-activation.gotmpl
values/jobs/e2e.gotmpl
values/jobs/keycloak.gotmpl
values/loki/auth-config.gotmpl
values/minio/minio.gotmpl
values/oauth2-proxy/oauth2-proxy.gotmpl
values/otomi-api/otomi-api.gotmpl
values/otomi-pipelines/otomi-pipelines.gotmpl
values/prometheus-operator/prometheus-operator.gotmpl
values/prometheus-operator/thanos-minio-config.gotmpl
values/team-ns/team-ns.gotmpl
values/tempo/tempo.gotmpl
values/thanos/thanos-minio-config.gotmpl
values/velero/velero.gotmpl

This PR fixes the Helm templates by adding quotes around sensitive values to prevent syntax errors during template rendering.
Implement:  [APL-577](https://jira.linode.com/browse/APL-577)
Testing: [Ticket comment](https://jira.linode.com/browse/APL-577?focusedId=588385&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-588385)

fix: quote sensitive values in Helm templates

---

values/prometheus-msteams/prometheus-msteams.gotmpl
values/prometheus-operator/prometheus-operator.gotmpl
values/promtail/promtail.gotmpl

fix: small fixes in go templates

---

charts/base/templates/clusterrole.yaml
charts/team-ns/templates/rbac.yaml
charts/tekton-triggers/templates/release/clusterroles.yaml

Strengthen the RBAC of the team scoped namespaces.

feat: replace clusterrole for secrets with namespaced role and removed ingress update clusterrole

---

values/istio-gateway/istio-egressgateway.yaml.gotmpl
values/istio-gateway/istio-ingressgateway.yaml.gotmpl
values/istiod/istiod.gotmpl

After the transition from Istio Operator to Istio chart and upgrade few configuration parameters have been lost.
- Deployment strategy for Istio gateways
- podDisruptionBudget for Istio gateways
- priorityClassName for istiod
These findings were revealed while comparing manifests from to live APL instances.

fix: restore istiod configuration 

---

.editorconfig

Adding .editorconfig for some code editor agnostic standards.

chore: added .editorconfig

---

tests/fixtures/env/teams/demo/sealedsecrets/my-secret.yaml
versions.yaml

This PR updates the sealed secrets sample file in tests/fixtures team-demo folder.
Ticket: https://jira.linode.com/browse/APL-538
PRs: [apl-api](https://github.com/linode/apl-api/pull/739) | [apl-console](https://github.com/linode/apl-console/pull/573)

fix: sealed secrets sample file

---

chart/apl/templates/cleanup-job.yaml
chart/apl/values.yaml
values/k8s/k8s-raw.gotmpl

feat: add post-install cleanup job

---

Dockerfile
package-lock.json
src/common/crypt.ts
tools/Dockerfile

fix: incompatibility between helm and helm-secrets

---

src/operator/k8s.test.ts
src/operator/k8s.ts

fix: update apply state

---

apps.yaml

fix: removed apl docs links from apps

---

chart/apl/templates/job.yaml

The welcome message looked a bit weird with this cleanup. This fixes that.

fix: suppress output during cleanup of ClusterRoleBinding

---

src/cmd/migrate.ts

fix: update helmfile template version in migration script for apl-operator

---

src/cmd/migrate.ts
values/prometheus-operator/prometheus-operator.gotmpl
values/prometheus-operator/rules/argocd.yaml

Rules that trigger alerts on app not synced or on argocd controller down.
In prometheus app, see two new alerts: 
- ArgoAppMissing
- ArgoAppNotSynced

feat: add argocd prometheus rules

---

.github/workflows/integration.yml

ci: workflow_dispatch with useORCS set tu true

---

versions.yaml

API and console should refer to `main`.

chore: reset versions to main

---

charts/team-ns/templates/tekton-tasks/git-clone.yaml
charts/team-ns/templates/tekton-tasks/grype.yaml

Adds ORCS support on missing tekton-tasks image defaults.

feat: adding ORCS support for tekton tasks

---

.github/workflows/integration.yml

fix: deploying apl

---

charts/otomi-db/templates/backup.yaml
charts/otomi-db/templates/cluster.yaml
charts/otomi-db/templates/objectstore.yaml
charts/otomi-db/values.yaml
helmfile.d/snippets/defaults.yaml
tests/fixtures/env/apps/cnpg.yaml
values-schema.yaml
values/gitea/gitea-otomi-db.gotmpl
values/harbor/harbor-otomi-db.gotmpl
values/keycloak/keycloak-otomi-db.gotmpl

This is a follow-up to #2299, making the changes optional. This was necessary, due to the sidecar execution failing on some clusters for yet unknown reasons.

feat: optionally use cnpg backup plugin

---

ci/src/update-helm-chart-deps.mjs

This PR fixes an invalid variable reference in the chart upgrade script.

ci: fix variable name in upgrade script

---

chart/chart-index/Chart.yaml
ci/src/update-helm-chart-deps.mjs

This PR fixes an issue, where apps.yaml includes several version changes where there should only be one. This happens if multiple updates are found within the same run.

ci: fix apps side effect

---

ci/src/update-helm-chart-deps.mjs

Fixes an issue with running custom functions after chart upgrades. Currently this affects only the Kyverno chart.

ci: fix post-upgrade function

---

.github/workflows/integration.yml

fix: do setup wiz after checkout
