linode/apl-core

- bin/check-console.sh
As established by me and @Morriz, without exporting variables in bin/check-console.sh in some shells these variables aren't available in the global namespace. This occurs when variables are added to the /tmp/otomi-env file, and subsequently get deleted by the rm /tmp/otomi-values command. This has been reproduced on my computer and is a shell quirk, but it's not clear what environment causes it. To be sure, exporting these values will cover more edge cases.
> fix: without `export $..` environment variables are not available

- bin/otomi
Relating to #228. This modification will execute `otomi decrypt` without parameters as `drun bin/crypt.sh decrypt` which will decrypt all files in `otomi-values`.
> fix: modify check empty parameters

- tools/Dockerfile
Copy the yq binary directly from the developers own docker image, this way ppa is no longer required
and other dependencies can be removed, and the two run apt install layers can be merged into one.
fix #272
> refactor: don't require ppa, but get yq from developer's docker image

- values-schema.yaml
- values/jobs/keycloak.gotmpl
As discused, I added `IDP_USERNAME_CLAIM_MAPPER` environment variable which can be used for the `Username` field mapping on user registration stage.
Updated Values repo with default value of `IDP_USERNAME_CLAIM_MAPPER="${CLAIM.email}"` but it can also be `"${CLAIM.oid}"`.
> feat: add configurable username claim mapper

- values-schema.yaml
It is quite painful to provide values to otomi-values repo for new charts, because `otomi validate-values` will rise an error, e.g.:                                                                                         
```
[
{
keyword: 'additionalProperties',
dataPath: '.charts',
schemaPath: '#/properties/charts/additionalProperties',
params: { additionalProperty: 'vault' },
message: 'should NOT have additional properties'
}
]
```
I would really appreciate if we can make schema more permissive for new charts names, so developers do not stumble on "chicken egg" problem and can provide working settings to values repo that can accompany PRs in otomi-core.
> feat: allow adding new charts even if they are not defined in the schema spec

- helmfile.d/helmfile-60.teams.yaml
A brand new team that is onboarded may not have any service in the cluster.
This change prevents the following error:
```
in helmfile.d/helmfile-60.teams.yaml: error during helmfile-60.teams.yaml.part.1 parsing: template: stringTemplate:91:41: executing "stringTemplate" at <$team.services>: map has no entry for key "services"
```
> fix: team services may not exist

- charts/jobs/templates/configmap.yaml
- charts/jobs/templates/job.yaml
- values/jobs/gitea.gotmpl
Fixes #338 
Create a separate init configmap, so env variables aren't shared and don't cause collision.
> Job env variables

- profiles/aws/env/secrets.settings.yaml
- values-schema.yaml
I created this pull request because the `otomi-api` schema will rely on this schema. @j-zimnowoda made it clear that we don't want divergence in the schemas and I agree of course.
The story: The `openapi-generator` was complaining about this schema. At first I assumed that this schema is valid JSON schema but not OpenAPI schema, but I can't find anything about the previous modification being valid any schema.
An `oneOf` takes an array of subschemas, and not an array of objects. It is not possible to use `$ref` anywhere one likes. "`$ref` can only be used in place of a subschema."
If this breaks anything, how can we integrate it?
> KMS schema is not valid JSON Schema/OpenAPI schema

- bin/otomi
While porting the CLI I found that there were 3 mistakes in the argument parsing, posting a quick hot-fix, but will no longer be present in the new CLI
> Fix variable expansion

- values/otomi-console/otomi-console.gotmpl
This is the new release for `otomi-console` without the red screen error.
> Bump semver to 0.4.51

- chart/otomi/Chart.yaml
Chart doesn't work because of the change in cluster.owner and we need to release a new chart version.
> fix: releasing a chart after adding cluster.owner

- binzx/otomi
- src/common/envalid.ts
- src/common/gitea-push.ts
- src/common/utils.ts
- src/common/yargs-opts.ts
- src/otomi.ts
Found a critical bug in gitea-push, because of refactoring of CLI it was now exiting, whereas it should throw an error and exit on an undefined variable.
Fixed in this PR
> fix: 🐛 gitea-push, after refactor process exit wast ran

- .values/env/charts/secrets.gitea.yaml
- .values/env/charts/secrets.harbor.yaml
- .values/env/charts/secrets.keycloak.yaml
- .values/env/charts/secrets.kubeapps.yaml
- .values/env/charts/secrets.loki.yaml
- .values/env/charts/secrets.oauth2-proxy.yaml
- .values/env/cluster.yaml
- chart/otomi/localtest.sh
- values/otomi-api/otomi-api.gotmpl
Empty keys in value skeleton makes validation problem after merging with otomi chart values if user doesn't provide values for those empty keys.
> fix: removing empty keys from value skeleton

- src/server/index.ts
Point to `ENV_DIR`, doesn't need to be hardcoded as it is passed to ENV_DIR as well.
Idem for `rootDir`
> Quickfix otomi server start 

- binzx/otomi
- src/server/index.ts
#256
Fix server symlink, needs to check for symlink even if ENV_DIR exists.
Also add fix for @mojtabaimani's `wc -l` containing spaces issue
> fix: otomi server create symlink

- values/gitea/gitea.gotmpl
Based on #591 any user was able to register.
Now only OIDC users are allowed to register, thus limiting the users allowed by keycloak.
The admin user can still sign-in.
Deployed on eks-dev, so you can see it in live environment.
Closes #591
> Disable non-OIDC gitea user registration

- binzx/otomi
Issue messaged to me by @srodenhuis 
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ts-node' imported from /home/app/stack/
at new NodeError (node:internal/errors:363:5)
at packageResolve (node:internal/modules/esm/resolve:712:9)
at moduleResolve (node:internal/modules/esm/resolve:753:18)
at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:867:11)
at Loader.resolve (node:internal/modules/esm/loader:89:40)
at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)
at Loader.import (node:internal/modules/esm/loader:177:28)
at node:internal/process/esm_loader:57:31
at initializeLoader (node:internal/process/esm_loader:62:5)
at Object.loadESM (node:internal/process/esm_loader:67:11) {
code: 'ERR_MODULE_NOT_FOUND'
}
```
This has to do that `/home/app/stack` …
> fix: 🐛 Package is not core if /home/app/stack path is used

- binzx/otomi
- src/cmd/bootstrap.ts
- src/common/utils.ts
Some folks has experienced the following error while bootstrapping values
```
TypeError: Cannot convert undefined or null to object
at Function.entries (<anonymous>)
at Object.flattenObject (/Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/src/common/utils.ts:300:17)
at /Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/src/common/utils.ts:303:70
at Array.flatMap (<anonymous>)
at Object.flattenObject (/Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/src/common/utils.ts:301:6)
at /Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/src/common/utils.ts:303:70
at Array.flatMap (<anonymous>)
at Object.flattenObject (/Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/src/common/utils.ts:301:6)
at Object.gucci (/Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/src/common/uti …
```
> Fix ambiguous error on bootstrap

- helmfile.d/snippets/derived.gotmpl
- package-lock.json
- src/common/utils.ts
- values/gitea/gitea.gotmpl
- values/jobs/harbor.gotmpl
- values/oauth2-proxy/oauth2-proxy-raw.gotmpl
- values/oauth2-proxy/oauth2-proxy.gotmpl
- values/otomi-api/otomi-api.gotmpl
- values/prometheus-operator/prometheus-operator.gotmpl
- values/vault-operator/vault-operator-raw.gotmpl
This PR contains fixes for:
https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/redkubes/otomi-core/483
https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/redkubes/unassigned-issues/352
Moved logic for deriving openId settings to `_derived` property
I did test on AWS with quickstart and saw that issue with gitea is gone. 
And I also observed that otomi apply is waiting for DNS record propagation.
Since these issues were caused by some race condition, I would like to ask you test it as well before merging.
Feel free to contribute to this PR to make it better;)
> Waitfor keycloak

- values-schema.yaml
##
Closes https://github.com/redkubes/unassigned-issues/issues/268.
> fix: harbor login

- charts/gatekeeper-operator/templates/post-job.yaml
Gatekeeper issues its own local certificates, so job always use --insecure flag
> fix: gatekeeper post job

- values-schema.yaml
This reverts commit d2af293ba179964e45ac77aa158608aee1e2b977.
Unfortunately the sprig implementation of htpasswd function does not support arguments:
```
otomi:generateSecrets:info Second round of templating +2ms
otomi:global:error Error: Error parsing template(s): template: -:33: bad number syntax: "-n"
otomi:global:error     at Object.gucci (/Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/src/common/utils.ts:335:30)                                   
```
See alos:
http://masterminds.github.io/sprig/crypto.html#htpasswd
https://github.com/Masterminds/sprig/commit/173256c8049ac8beac7984a7a51f5361c1c5078c
> Revert "fix: harbor login (#661)"

- src/cmd/bootstrap.ts
- src/common/utils.ts
- values-schema.yaml
> fix: ensure path existence

- chart/otomi/values-production.yaml
- helmfile.d/snippets/defaults.yaml
- tests/fixtures/env/charts/knative.yaml
- values-schema.yaml
- values/istio-operator/istio-operator-raw.gotmpl
- values/knative/knative-serving-raw.gotmpl
- values/nginx-ingress/nginx-ingress-private.gotmpl
- values/nginx-ingress/nginx-ingress.gotmpl
https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/redkubes/otomi-console/123
If this is approved then I will make another PR to otomi-api
> feat: expose values for knative serving replicas

- charts/otomi-api/templates/deployment.yaml
- charts/otomi-api/values.yaml
- charts/otomi-console/templates/deployment.yaml
- charts/otomi-console/values.yaml
- values/otomi-api/otomi-api.gotmpl
> fix: api and console only need podsecuritycontext

- charts/team-ns/templates/istio-virtualservices.yaml
- core.yaml
- values-schema.yaml
https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/redkubes/unassigned-issues/349
As a result of this change:
- the deployment time of the platform takes 13 minutes.
- the JWKS issue is removed
> Fix removing authz header

- values/prometheus-operator/prometheus-operator.gotmpl
In [CVE-2021-43798](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-43798) a solution is given for the vulnerability in current grafana version. The image
has to be upgraded to 8.0.7 asap
> fix(grafana): grafana patch 8.0.3 to 8.0.7 for CVE-2021-43798

- values/kubernetes-external-secrets/kubernetes-external-secrets.gotmpl
Refer to: https://github.com/external-secrets/kubernetes-external-secrets/issues/826
> fix: downgrade kes

- tests/fixtures/env/charts/otomi-api.yaml
- tests/fixtures/env/charts/otomi-console.yaml
- values-schema.yaml
removing image attribute from otomi-conole and otomi-api
> fix(remove image attribute): removing image atteibute in console and api

- values-schema.yaml
> fix(values-schema.yaml): fix #736

- helmfile.d/snippets/blackbox-targets.gotmpl
prometheus-blackbox-exporter is running in monitoring namespace, not in team namespaces.
fix #792
> fix(blackbox-exporter): fix: #792

- .github/workflows/integration-check.yml
- .github/workflows/integration.yml
- .github/workflows/main.yml
- chart/otomi/templates/job.yaml
- tests/integration/full.yaml
- tests/integration/minimal.yaml
This PR implements redkubes/unassigned-issues#418.
The following might want to be changed, but is possibly out of scope of this issue:
> ci: run integration test in GitHub actions

- values-schema.yaml
- versions.yaml
This is a fix for #845 
Tested and it works but one thing to be VERY careful about is that when you add an external provider for storing unseal secrets, that it will delete the kubernetes secret containing the keys **without** pushing them to keyvault, so you absolutely need to take a backup of that key before enabling this configuration.
I have included a warning in the field description in the values schema to help people avoid losing their keys (in both Core and API).
[Respective PR in API](https://github.com/redkubes/otomi-api/pull/316)
> fix: azure vault unseal

- .github/workflows/integration.yml
- .github/workflows/main.yml
- chart/otomi/Chart.yaml
Users trying to install otomi 
```
helm install otomi chart/otomi --dry-run --values <path>
```
,where `chart/otomi ` is a directory in `otomi-core`, experience the following error:
```
Error: INSTALLATION FAILED: validation: chart.metadata.version "0.5.CHART_PATCH_PLACEHOLDER" is invalid
```
This change enables helm chart installation without need of changing the value of `chart.metadata.version`
> fix: chart version placeholder conformed with semver

- values/vault-operator/vault-operator-raw.gotmpl
> fix: vault policies syntax

- .github/workflows/integration.yml
- tests/integration/full.yaml
- tests/integration/minimal.yaml
I introduced OTOMI_VERSION_PLACEHOLDER to insure `tools` container from otomi-api pod contains right version of otomi-core.
The `ha` flag is needed as otomi deployment may fail if Kubernetes-api in not in HA mode
The scheduled integration tests are run at midnight, thus it is better to set k8s maintenance-window later.
> ci: otomi version

- apps.yaml
> fix: missing appinfo, titles added

- values/gitea/gitea.gotmpl
This fixes the issue where the pv size for Gitea Postgress was not set in case the provider is not vultr.
> fix: gitea postgres pv size

- binzx/otomi
Running Otomi Cli as the root user is a big troublemaker. Otomi mounts ENV_DIR and creates files that are owned by the running user - `root`. Later a user that wants to work with values repo cannot change files from the ENV_DIR. It is extremely cumbersome for any kind of pipeline system which tries to cleanup files after execution as it does it as non-root user.
This PR by default runs docker container with the group and user ID of the host user (in case the host is Linux OS). A user may not exists in the docker container and that is fine as long as the underlining application does not try to read user metadata. That is our case, which I tested while integrating Otomi CLI with the azure DevOps pipeline.
A user may still define any other user IDs by exporting the `DOCKER_RUN_AS` variable.
> feat: otomi cli run as host user

- values/prometheus-operator/prometheus-operator.gotmpl
> fix: do not scrape kube metrics by default

- helmfile.d/snippets/defaults.yaml
- values-schema.yaml
- values/prometheus-operator/prometheus-operator.gotmpl
- values/vault-operator/vault-operator-raw.gotmpl
> fix: prometheus, vault, harbor schemas and values

- src/cmd/bootstrap.ts
- values-changes.yaml
- values-schema.yaml
> fix: values migration

- helmfile.d/helmfile-02.init.yaml
- helmfile.d/snippets/ingress-nginx-raw.gotmpl
- tests/fixtures/env/apps/ingress-nginx.yaml
Since introduction of ingress classes feature the `_rawValues` were not populated to the chart values.
This PR allows users to set `_rawValues` that applies to all `ingress-nginx-<name>` releases.
> feat: raw values for ingress-nginx chart

- versions.yaml
> fix: otomi-api pod gets stuck during pod initialization

- .github/workflows/integration.yml
Allow developers to create k8s cluster and install Otomi via GitHub pipeline.
> test: allow developers to create k8s cluster and install Otomi via GitHub pipeline

- tests/fixtures/env/apps/cert-manager.yaml
- values/cert-manager/cert-manager-raw.gotmpl
The ClusterIssuer was referencing a secret that did not exist in cert-manager namespace.
This issue was happening if dns configuration together with cert-manager lets encrypt issuer were provided via values.
> fix: missing secret for cert-manager

- values-schema.yaml
The schema did not complain about incorrect dns values. E.g.:
```
dns:
provider:
azure:
aadClientId: 00-aadClientId
resourceGroup: external-dns
subscriptionId: 00-subscriptionId
tenantId: 00-tenantId
domainFilters:
- otomi.cloud
```
which is incorrect, because the `domainFilters` is not in the right scope. Should be:
```
dns:
provider:
azure:
aadClientId: 00-aadClientId
resourceGroup: external-dns
subscriptionId: 00-subscriptionId
tenantId: 00-tenantId
domainFilters:
- otomi.cloud
```
> fix: do not allow additional properites at dns provider

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 0.16.18

- .github/workflows/integration-on-schedule-dns.yml
- .github/workflows/integration-on-schedule-full.yml
- .github/workflows/integration-on-schedule-minimal.yml
- .github/workflows/integration.yml
- tests/fixtures/env/secrets.settings.yaml
- tests/fixtures/env/settings.yaml
- tests/integration/full.yaml
- tests/integration/minimal.yaml
This PR enables users to schedule on demand Otomi deployment with customisable deployment scenarios like in the picture below. The deployment workflow ensures unique cluster.domianSuffix.
Moreover this PR implements scheduled test to ensure deployment with DNS is successful (see `.github/workflows/integration-on-schedule-dns.yml` file)
> test: integration tests and tests on demand with optional settings for dns kms and oidc

- values/vault-operator/vault-operator-raw.gotmpl
> fix: rename default vault secret name

- .github/workflows/integration.yml
Example 
cluster name instead of `i-3280617043-161-1-0-361b86c3808e4c501e95cb19439de6b125e2afa8`
will be called `i-3280617043`
> test: simplify cluster name

- .github/workflows/integration.yml
Turns out that the `github.run_id` was not enough to ensure cluster name uniqueness.
> test: ensure cluster name uniqueness for jobs using matrix strategy

- helmfile.d/helmfile-15.ingress-core.yaml
- tests/fixtures/env/teams/services.admin.yaml
> fix: admin services should not be excluded from team-ns-admin

- package.json
> fix: setting up NODE_ENV for lint:hf command

- core.yaml
This PR will enable Jaeger to be shared and made available for teams and remove Keycloak as a team app.
> feat: make Jaeger shared

- helmfile.d/helmfile-60.teams.yaml
- tests/fixtures/env/teams.yaml
- values-schema.yaml
- values/prometheus-operator/prometheus-operator-team.gotmpl
- versions.yaml
This PR brings:
- The option to disable the monitoring stack (grafana, prometheus) for a specific team when otomi is running in multi-tenant mode
> feat: add a flag to disable monitoring stack for a specific team

- .github/workflows/integration.yml
The pipeline by default provides GitHub credentials to pull images from the GitHub cache registry, which is good for testing with unofficial container image tags. However the GiHub cache repo does not contain images that has been release long time ago.
This PR checks if requested image tag is semver compatible (a simplified regex). If so then the Otomi installation job will pull container image from DockerHub.
> test: workflows select image registry [ci skip]

- .github/workflows/integration-on-schedule-full.yml
- .github/workflows/integration-on-schedule-minimal.yml
> test: digital ocean does not support k8s 1.22 anymore [ci skip]

- charts/drone/templates/deployment-agent.yaml
- charts/drone/templates/deployment-server.yaml
fixes #950
This PR removes annotations that may cause drone pipeline not being able to finalise the deployment job due to self-update deadlock.
Before Otomi upgrade, an operator needs to remove deprecated annotations from drone server and agent deployments.
> fix: do not redeploy drone on secret.yaml change

- .prettierignore
- CHANGELOG.md
- package-lock.json
- package.json
- versions.yaml
> chore(release): 0.16.20

- charts/drone/templates/deployment-agent.yaml
- charts/drone/templates/deployment-server.yaml
- src/cmd/bootstrap.ts
- src/cmd/gen-drone.ts
- src/common/values.ts
- values/drone/drone.gotmpl
- versions.yaml
> fix: generating drone pipeline file

- src/cmd/upgrade.test.ts
- src/cmd/upgrade.ts
- src/common/utils.test.ts
I noticed that all upgrade scripts are applied always during the apply step.
This PR fixes filtering out the not relevant upgrade versions.
> fix: upgrade only relevant versions

- src/server.ts
- versions.yaml
fixes #975
depends-on https://github.com/redkubes/otomi-api/pull/355
> fix: encrypt brand new secrets files

- src/server.ts
This reverts commit 900cf417b19a857bc6fa160e27f425aa094e05b5.
> Revert "fix: encrypt brand new secrets files (#1002)"

- upgrades.yaml
- vendor/kes-to-eso/migrate-post.sh
I improved upgrade script so it does not kickoff if the external-secrets release is not present.
> fix: external-secrets migration script

- chart/otomi/values.yaml
- tests/fixtures/env/secrets.settings.yaml
- tests/fixtures/env/settings.yaml
- values/cert-manager/cert-manager-raw.gotmpl
fixes logic to create external-dns secret for non Azure providers
> fix: certmanager secrets

- .vscode/launch.json
- src/cmd/apply.ts
- src/cmd/upgrade.ts
- src/common/utils.ts
- src/common/values.ts
- src/playground.ts
This is an enhancement to the upgrade script that prevents upgrading on very first otomi installation
Moreover in case of any development branch the upgrade will get the otomi version from the package.json.
There is also a playground file that make it easy to debug a give piece of code without the need to run any otomi command.
> fix: do not upgrade on very first install

- values/harbor/harbor.gotmpl
> fix: harbor registry htpasswd

- upgrades.yaml
- values/operator-lifecycle-manager/operator-lifecycle-manager.gotmpl
> fix: set olm target namespace

- helmfile.d/snippets/defaults.yaml
- versions.yaml
Increase default replica counts so as not to block nodes draining during k8s upgrade.
Notes:
- Gatekeeper controller manager does not support HPA, so the only practical option is to set a static default of 2
- Since istio ingress-gateway is already set to 2 replicas minimum in HPA, I have done the same for the egress gateway, because if egress gateway is enabled it could cause the same issue
> fix: scaling defaults

- helmfile.d/snippets/templates.gotmpl
- values/cluster-autoscaler/cluster-autoscaler.gotmpl
Cluster autoscaler is OOM Killed in a crash loop. 
Resource is increased to 256 MBi
> fix: cluster autoscaler memory requests

- helmfile.d/helmfile-02.init.yaml
- helmfile.d/snippets/derived.gotmpl
- tests/fixtures/env/cluster.yaml
> fix:  aws-ebs-csi-driver without dependency on  snapshot-controller and disabled by default 

- .github/workflows/integration-on-schedule-dns-no-admin-pass.yml
- .github/workflows/integration-on-schedule-dns.yml
- .github/workflows/integration-on-schedule-full.yml
- .github/workflows/integration-on-schedule-minimal-no-admin-pass.yml
- .github/workflows/integration-on-schedule-minimal.yml
- .github/workflows/integration.yml
- tests/integration/minimal.yaml
This allows the user to choose to either generate an admin password, or to use the default one.
Also adds test scenarios.
Related to #1055
> feat: extend integration test actions and scheduled tests with optional adminPassword

- helmfile.d/snippets/defaults.yaml
- tests/fixtures/env/settings.yaml
- values-schema.yaml
- versions.yaml
implements: https://github.com/redkubes/unassigned-issues/issues/567
> feat: set the default value of the isMultitentat flag

- src/cmd/bootstrap.test.ts
- src/cmd/bootstrap.ts
This PR:
- adds a fix for not supplying a VALUES_INPUT and breaking drone runner
> fix: added check for values input

- values/velero/velero.gotmpl
This PR fixes the configuration of the region setting for using AWS S3 in Velero
> fix: aws region cfg 4 velero

- binzx/otomi
When you try to run otomi core without docker running you get the generic error message saying "Something went wrong when trying to pull '[otomi-core:branch]'". Although there might be multiple reasons to throw this error, the majority of reasons is that docker is simply not running, by adding a little bit of text at the end with the question if docker is running it might save a lot of time debugging.
> feat: improved error message

- values/harbor/harbor.gotmpl
This fixes multi-attach errors when updating the harbor jobservice, and also sets the priorityClass for Harbor services to "otomi-critical" where before it was default
> fix: harbor priorityclass and updatestrategy

- .github/workflows/integration.yml
Added `1.23` option into workflow dispatch in order to support previous versions.
> ci: Add k8s 1.23 option to workflow dispatch within github actions Integration Job

- helmfile.d/snippets/defaults.yaml
- values-schema.yaml
- values/harbor/harbor.gotmpl
Requires redkubes/otomi-api#395
Allow user to specify resource quota for harbor trivy, also increase quota from helm chart defaults.
The chart default CPU + mem _requests_ were extremely low, which meant that the pod could be scheduled to nodes incapable of providing the resources specified in the _limits_, thereby disrupting the scans of images with larger layer sizes.
> fix: add resources for trivy scanner

- charts/team-ns/templates/istio-virtualservices.yaml
In the case where the value is an asterisk (*), the value will fail tests.
This is due to how the templator handles strings starting with an asterisk - even if quoted in the values file, the quotes are stripped during templating, and passed to Helm as a bare asterisk, which is not valid here.
This is the error but the line numbers are not relevant;
`  otomi:global:error   Error: YAML parse error on team-ns/templates/istio-virtualservices.yaml: error converting YAML to JSON: yaml: line 45: did not find expected alphabetic or numeric character`
Fails:
My hacky workaround - Passes tests and works correctly
> fix: Istio VirtualService response header parsing

- charts/argocd-operator/templates/catalog_source.yaml
- charts/argocd-operator/templates/subscription.yaml
This PR enforces usage of certain argocd-operator, so argocd applicationset controller is deployed properly.
However this PR does not downgrade the controller that has already been upgraded to v0.6.0 which seems to be broken.
> feat: olm channel

- chart/otomi/templates/values-secrets.yaml
- versions.yaml
This PR adds logic to set the otomi version to the one specified in Charts.appVersion when its not specified  by the user
> fix: otomi version tag update

- chart/otomi/values.yaml
- values-schema.yaml
To install Otomi on Scaleway, we need a new provider. By using the Scaleway provider, metrics-server is not enabled (because Scaleway already runs metrics-server by default)
> feat: scaleway provider

- charts/team-ns/templates/rules/prometheus-rules.yaml
Fixes templating issues while team does not have the `billingAlertQuotas` defined in the values repo.
```
STDERR:
Error: template: team-ns/templates/rules/prometheus-rules.yaml:18:145: executing "team-ns/templates/rules/prometheus-rules.yaml" at <$v.billingAlertQuotas.teamCpuMonthQuotaReached.quota>: nil pointer evaluating interface {}.teamCpuMonthQuotaReached
COMBINED OUTPUT:
Release "team-ns-demo" does not exist. Installing it now.
Error: template: team-ns/templates/rules/prometheus-rules.yaml:18:145: executing "team-ns/templates/rules/prometheus-rules.yaml" at <$v.billingAlertQuotas.teamCpuMonthQuotaReached.quota>: nil pointer evaluating interface {}.teamCpuMonthQuotaReached
at hfCore (/home/app/stack/dist/src/common/hf.js:44:30)
exit code: 1
at ChildProcess.<anonymous> …
```
> fix: team billing quota defaults

- helmfile.d/helmfile-03.init.yaml
- helmfile.d/helmfile-09.init.yaml
Solves error:
```
STDERR:
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "internal-harbor-token-service-ca" namespace: "harbor" from "": no matches for kind "Certificate" in version "cert-manager.io/v1"
ensure CRDs are installed first
```
> fix: deploy harbor cert after certmaneger crds are deployed

- .github/workflows/integration-on-schedule-full.yml
- README.md
- chart/otomi/values.yaml
- docs/development.md
- values-schema.yaml
> fix: schema with supported k8s versions

- charts/team-ns/templates/rbac.yaml
- versions.yaml
> feat: define kubectl SA for each team

- helmfile.d/snippets/defaults.yaml
- helmfile.d/snippets/derived.gotmpl
- values-changes.yaml
The code from this PR will only work after the https://github.com/redkubes/otomi-core/pull/1131 is merged to main and reflected in other PRs.
This code sets default database type to `external`
The `values-changes.yaml` file defines a migration that happens only once and only for existing otomi instance.
In this way we prevent existing harbor instance to switch to external database upon Otomi upgrade.
There is only one disadvantage that the migration will also happens if harbor is not enabled but we can accept it as it is not harmful.
> feat: add migration rules for harbor db type

- charts/otomi-api/templates/clusterrole.yaml
- charts/team-ns/templates/rbac.yaml
Since k8s 1.24 the SA token are not autogenerated by default. 
There are three use cases that needs to be covered:
- k8s cluster is 1.23
- k8s cluster is 1.24 with SA token autogeneration disabled
- k8s cluster is 1.24 with SA token autogeneration enabled
This solution aims to cover above scenarios. The users can observe the `kubectl` SA with either one or two secrets depending if autogeneration enabled or disabled.
```
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
name: kubectl
namespace: team-demo
secrets:
- name: kubectl-token
- name: kubectl-token-t84qg
```
```
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
name: kubectl
namespace: team-demo
secrets:
- name: kubectl-token
```
> fix: service account for generating kubeconfig

- helmfile.d/snippets/alertmanager.gotmpl
This PR fixes #1094 for the platform alertmanger (not for the team alertmanager)
> fix: run platform alertmng without receiver

- helmfile.d/snippets/defaults.yaml
- tests/fixtures/env/apps/istio.yaml
- tests/kind/env/apps/istio.yaml
- values-schema.yaml
- values/istio-operator/istio-operator-raw.gotmpl
This change allows full control over the service mesh configuration throw the values repo.
> feat: allow to configure istio mesh config

- helmfile.d/snippets/alertmanager.gotmpl
Some logic improvements to enable the "null" receiver when no receiver is configured in Otomi
> fix: alert manager default receiver

- values-schema.yaml
- values/thanos/thanos.gotmpl
Add azure blob storage for Thanos
> feat: add azureblob for thanos

- charts/prometheus-blackbox-exporter/Chart.yaml
- charts/prometheus-blackbox-exporter/OWNERS
- charts/prometheus-blackbox-exporter/README.md
- charts/prometheus-blackbox-exporter/ci/extraenv-values.yaml
- charts/prometheus-blackbox-exporter/ci/hostAliases.yml
- charts/prometheus-blackbox-exporter/ci/icmp-values.yaml
- charts/prometheus-blackbox-exporter/ci/networkpolicy-values.yaml
- charts/prometheus-blackbox-exporter/templates/NOTES.txt
- charts/prometheus-blackbox-exporter/templates/_helpers.tpl
- charts/prometheus-blackbox-exporter/templates/configmap.yaml
- charts/prometheus-blackbox-exporter/templates/daemonset.yaml
- charts/prometheus-blackbox-exporter/templates/deployment.yaml
- charts/prometheus-blackbox-exporter/templates/extra-manifests.yaml
- charts/prometheus-blackbox-exporter/templates/ingress.yaml
- charts/prometheus-blackbox-exporter/templates/networkpolicy.yaml
- charts/prometheus-blackbox-exporter/templates/poddisruptionbudget.yaml
- charts/prometheus-blackbox-exporter/templates/podsecuritypolicy.yaml
- charts/prometheus-blackbox-exporter/templates/prometheusrule.yaml
- charts/prometheus-blackbox-exporter/templates/role.yaml
- charts/prometheus-blackbox-exporter/templates/rolebinding.yaml
- charts/prometheus-blackbox-exporter/templates/selfservicemonitor.yaml
- charts/prometheus-blackbox-exporter/templates/service.yaml
- charts/prometheus-blackbox-exporter/templates/serviceaccount.yaml
- charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml
- charts/prometheus-blackbox-exporter/values.yaml
> feat: upgrade prometheus blackbox exporter

- .github/workflows/cloudtty-build-push.yml
The default fetch-depth of the "actions/checkout@v3" is '1', so when we checked for the files modified in the last commit it was showing all the files in the repo. This way the third if condition was being triggered and bumped the patch version on every commit to the main branch. 
Setting the fetch-depth to '2' solves the issue by comparing the last commit with the previous one. This way the 3rd if condition is validated correctly.
I also rewrote the git command for a more programatic  one and added some echo to show the version change.
> fix: cloudtty image versioning

- upgrades/pre/upgrade-0-22-0.sh
The script will uninstall the "prometheus-operator" release before upgrading to any otomi version prior to 0.22.0.
> fix: added upgrade script for kube prom stack

- core.yaml
Fix for ingress configuration to enable remote-write to Thanos for external clusters
> fix: thanos receive ingress path

- charts/team-ns/templates/rbac.yaml
This MR will fix the tty role so users can access all apiGroups in their namespace. If we don't define '*' than the role gives access only to the core apiGroup.
> fix: added all apiGroups instead of only core

- apps.yaml
- charts/istio-operator/Chart.yaml
- charts/istio-operator/files/gen-operator.yaml
- charts/istio-operator/templates/deployment.yaml
- charts/istio-operator/values.yaml
> feat: upgrading istio-operator to 1.17.4

- .vscode/launch.json
- Dockerfile
- package.json
- src/cmd/migrate.test.ts
- src/common/values.test.ts
- src/common/values.ts
- tools/Dockerfile
- values-schema.yaml
Fixes issue with E2BIG that happens if values repo bitumen too big.
The underlying issue is that all user values were converted to the shell parameters, reaching in this way shell limits.
This code changes ensures that values are not propagated as shell parameters.
> fix: gucci

- src/common/hf.ts
> feat: add --skip-cleanup argument while working in the development mode

- tests/integration/full.yaml
The metrics-server is installed automatically depending on the cloud provider.
> test: do not set metrics-server

- .github/workflows/integration-on-schedule-full.yml
- .github/workflows/integration-on-schedule-minimal-no-admin-pass.yml
- .github/workflows/integration-on-schedule-minimal-with-team.yml
- .github/workflows/integration-on-schedule-minimal.yml
- .github/workflows/integration-on-schedule-upgrade.yml
- helmfile.d/snippets/defaults.yaml
- tests/integration/upgrade.yaml
- values/jobs/e2e.gotmpl
This PR will perform the Otomi upgrade test from version `v0.24.0` to the one that is indicated by a user while selecting the branch in Github Actions for `Deploy Otomi` pipeline.
I also changed the cron job start time, as it is not possible to create 7 clusters at once due to the resource quota.
> test: otomi upgrade test scenario

- values/jobs/drone-activation.gotmpl
- values/jobs/e2e.gotmpl
https://github.com/redkubes/otomi-core/pull/1200
This PR fixes and disables video recordings for drone-activation and otomi-upgrade jobs.
Updated cypress scripts for drone-activation and otomi-upgrade jobs.
> fix: drone-activation

- .github/workflows/integration.yml
- .github/workflows/pr-lint.yml
This PR updates some of the remaining deprecated GitHub Actions in Otomi-Core.
#997
The Lint will still show a warning but that is because it doesn't use the newest version yet for this PR.
> fix: update deprecated actions

- charts/team-ns/templates/builds/buildpack.yaml
- charts/team-ns/templates/builds/docker.yaml
- charts/team-ns/templates/rbac.yaml
- tests/fixtures/env/teams/builds.demo.yaml
- tests/fixtures/rendered-values.yaml
- tests/integration/minimal-with-team.yaml
- tests/integration/upgrade.yaml
- values-schema.yaml
Remove repo access for Builds. Access for local Gitea will be enabled by default. This PR has a dependency with https://github.com/redkubes/otomi-api/pull/443
> fix: remove option for Gitea repo access for Builds

- values/loki/loki.gotmpl
The default memory limits for ingester are set to 1Gi
The `replay_memory_ceiling` should not be more that 75% of available memory. 
Read more: https://grafana.com/docs/loki/latest/operations/storage/wal/#backpressure
> feat: adjust loki wal backpressure

- charts/team-ns/templates/_helpers.tpl
- charts/team-ns/templates/_ingress.tpl
- charts/team-ns/templates/ingress.yaml
- core.yaml
- helmfile.d/helmfile-60.teams.yaml
- helmfile.d/snippets/domains.gotmpl
- package-lock.json
- src/cmd/template.ts
- src/common/hf.ts
- values/prometheus-operator/prometheus-operator.gotmpl
- versions.yaml
Before prometheus was exposed via `apps.<domainSuffix>` FQDN
Now prometheus is exposed via `prometheus.<domainSuffix>` FQDN
The `apps` host is no longer needed.
implements: #1260
> feat: prometheus with its own host

- tests/fixtures/env/apps/loki.yaml
- values-schema.yaml
- values/loki/loki.gotmpl
This PR adds the option to use an EC2 role to provide access to s3 for Loki storage (instead of providing credentials).
> feat: use ec2 role for loki s3 access

- src/cmd/destroy.ts
This PR aims to improve otomi destroy functionality by removing admission controllers that were installed by various operators.
It is important to do it because they may bock any further deployments to the cluster.
> feat: uninstall admission controllers

- core.yaml
This PR removes the debts for otel in core.yaml. Otel can be activated independent of enabled receivers of exporters
> fix: rm otel debts

- helmfile.d/helmfile-03.init.yaml
- helmfile.d/helmfile-09.init.yaml
Tekton triggers is dependent on `config.webhook.pipeline.tekton.dev` and sometimes this is not ready and install will fail. This PR fixes this
> fix: trigger helmfile.d order

- helmfile.d/helmfile-60.teams.yaml
- values/prometheus-operator/prometheus-operator.gotmpl
This PR fixes:
- the trace2log query for the tempo datasource config for teams
- missing double $ signs needed for YAML interpolation
> fix: trace2logs query

- values/istio-operator/istio-operator-raw.gotmpl
This change ensures that containers will not start until istio-proxy sidecar is ready.
By doing so, we mitigate the network issues "connection refused" that some applications does not handle well (e.g.: cloud native PG)
The side effect is that application start time will be a bit slower.
> feat: set holdApplicationUntilProxyStarts flag for istio

- charts/team-ns/templates/backup/schedule.yaml
To create backup schedules to backup PVs, it is required to set `includeClusterResources: true` and also include `pvc` to the list of resources. This PR fixes this.
> fix: incorrect defaults in backup schedule

- tools/Dockerfile
https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/gh/redkubes/otomi-core/1299
This PR updates the dockerfile node.js installation script for otomi tools. In the dockerfile deprecated installation script changed with the new one via the [instructions](https://github.com/nodesource/distributions).
- Run Docker Desktop
- Open integrated terminal in VS Code (otomi-core) 
- Run on your local `docker buildx build --load -t otomi/tools -f tools/Dockerfile .`
- Verify that `otomi-tools` image is builded successfully (without getting `SCRIPT DEPRECATION WARNING`)
Updated tools dockerfile.
> fix: dockerfile otomi tools script

- values/keycloak-operator/keycloak-operator-cr.gotmpl
Changes to support the use of a jar for the Otomi Keycloak theme.
> fix: use kc theme jar

- values/keycloak-operator/keycloak-operator-cr.gotmpl
This change fixes compatibility issue with keycloak theme, which prevent deploying Otomi from main.
> fix: keycloak theme

- charts/gitea/templates/gitea/statefulset.yaml
- helmfile.d/snippets/values-gitea-prepare.gotmpl
- tests/fixtures/env/apps/drone.yaml
- tests/fixtures/env/apps/gitea.yaml
- values/jobs/gitea-prepare.gotmpl
We noticed that in case of huge amount of teams in Otomi, the `job-gitea-prepare` fails with ambiguous message 
```
exec /bin/sh: argument list too long
```
After debugging this issue we realised that it is caused by an environment variable that exceeds the allowed size.
> feat: optimise generating gitea job configuration

- .github/workflows/integration.yml
This PR uses a private network id so that there are no longer private networks created with every deployment.
> fix: scaleway private network id

- helmfile.d/snippets/defaults.yaml
When using Keycloak operator, keycloak is build at each start. This is time consuming. To speed up the building process, more CPU is needed. This PR increases CPU limits for both Keycloak and Keycloak operator.
> fix: kc limits

- .github/workflows/scw-remove-clusters-dev-on-schedule.yml
This MR fixes the schedule deletion of the private networks in scaleway. It was previously failing because of the unescaped '(' character in the echo command.
> fix: escaped characters

- helmfile.d/snippets/defaults.yaml
Two replicas ensure smooth db Pod traversal between nodes.
E.g.: draining a node.
> feat: default two replicas of keycloak db

- charts/tekton-dashboard/templates/_helpers.tpl
- values-schema.yaml
The svc name of the tekton dasboard was limited to 26 characters and this limits team-names to be max 9 characters. By setting the svc name to 32 characters, team names now can be max 12 characters. I added the max team name to the docs.
> fix: svc name to max 14

- charts/team-ns/templates/tekton-tasks/buildpacks.yaml
- charts/team-ns/templates/tekton-tasks/git-clone.yaml
- charts/team-ns/templates/tekton-tasks/kaniko.yaml
With tekton enabled by default, tekton tasks should always be added.
> fix: team tekton tasks

- tools/Dockerfile-tty
This MR adds kubectl-cnpg to the tty console for working with cnpg clusters through the cli.
> feat: adding kubectl-cpng to the tty console

- charts/grafana-dashboards/k8s-teams/team-status.json
Fix team status dashboard query to make sure only the status is shown for team deployed containers
> fix: exclude prom in team status dashboard

- src/common/values.test.ts
- src/common/values.ts
- tests/bootstrap/input.yaml
- values/harbor/harbor.gotmpl
fixes #1398
This PR ensures that the `httpaswd` secret is always generated during the initial installation.
Note: it does not solve the issue on existing clusters. Only for new installations.
Tested with:
```
npm run bootstrap-dev
```
> fix: Harbor htpasswd bootstrap

- .github/workflows/main.yml
- chart/otomi/templates/job.yaml
- charts/otomi-pipelines/templates/tekton-otomi-git-clone.yaml
- charts/otomi-pipelines/templates/tekton-otomi-task.yaml
- core.yaml
This MR removes the resource limits for the otomi installer job and disables gatekeeper policy checks for the otomi-pipelines namespace.
> feat: updating otomi tasks and otomi installer job resource limits

- .github/workflows/main.yml
- charts/team-ns/templates/backup/schedule.yaml
This MR removes hardcoding of specific resources to be backed up by velero. Doing so insures that velero automatically backes up the PV/PVC. For more info check  this link (note the `includeClusterResources` comments): https://velero.io/docs/main/api-types/backup/#api-groupversion
> feat: update backup schedule definition

- values/oauth2-proxy/oauth2-proxy-raw.gotmpl
This PR fixes the oauth2-proxy ingress configuration when "Bring Your Own Certificate" is in use.
> fix: oauth2-proxy cert

- values/oauth2-proxy/oauth2-proxy-raw.gotmpl
This PR fixes the name of the tls secret to be used by the oauth2-proxy ingress in case the "byo-wildcard-cert" is used.
> fix: renamed the secret to be used by the ingress

- charts/team-ns/templates/istio-sidecar.yaml
- charts/team-ns/templates/networkpolicy.yaml
- helmfile.d/helmfile-60.teams.yaml
- values/prometheus-operator/prometheus-operator-team.gotmpl
If a team deploy's servicemonitors for the team's prometheus to scrape, prometheus needs access to the workload service. This PR adds:
- a default ingress policy for each service to allow access for prometheus
- a Sidecar resource for prometheus using a workload selector to overrule the default outboundTrafficPolicy
- add `otomi.io/app` label to the team's prometheus pod
> fix: team netpol for prom

- src/cmd/commit.ts
This PR adds a feature to remove `deployment` and `ksvc` folders while cloning into the gitea charts repository.
> feat: remove old charts while cloning into gitea

- helmfile.d/helmfile-60.teams.yaml
(cherry picked from commit 22472281a475feb7d862d7d924b84e1fbbd6d47d)
> feat: enable team prometheus prometheus is monitoringStack enabled

- helmfile.d/helmfile-60.teams.yaml
This PR improves the logic for team monitoring to make sure that:
- Alertmanager, Prometheus and Grafana are  installed for the team when monitoringStack.enabled=true, also when Prometheus and Grafana on the platform are not enabled
- Grafana is installed when platform prometheus.enabled=true so the team gets Grafana for dashboards using the platform Prometheus datasource
- Grafana additional datasources are configured based on platform availability of Loki, Prometheus and Tempo. If Grafana for the team is enabled, but Prometheus, Loki and Tempo on platform level are not enabled, then the team Grafana will only have the default datasource (for the team's Prometheus)
> fix: team monitoring logic

- src/cmd/commit.ts
Remove files after cloning otomi-charts
> fix: rm files in otomi/charts repo

- charts/team-ns/templates/builds/buildpack.yaml
- charts/team-ns/templates/builds/docker.yaml
- tests/fixtures/env/teams/builds.demo.yaml
- tests/fixtures/env/teams/workloads.demo.yaml
- values-schema.yaml
Now builds can only be created when using a repo in Gitea. To support the use of external private Git repo's, a user can now select to use a secret that contains the credentials of a external (like Github or Gitlab) private repo.
External public repo's and private repo's in Gitea are supported by default.
> feat: select secret for external private repo

- charts/otomi-pipelines/templates/tekton-otomi-task-teams.yaml
- helmfile.d/helmfile-15.ingress-core.yaml
- helmfile.d/helmfile-60.teams.yaml
- src/cmd/apply-as-apps.ts
- src/cmd/apply.ts
This PR aims to fix the following issues:
- team-ns-admin release should not be deployed by helmfile in otomi-tekton-task 
- otomi-tekton-task-teams should not break if there is no team defined
> fix: deploying teams

- charts/team-ns/templates/istio-sidecar.yaml
- charts/team-ns/templates/networkpolicy.yaml
- charts/team-ns/templates/servicemonitors/service-monitors.yaml
- tests/fixtures/env/teams.yaml
- tests/integration/minimal-with-team.yaml
- tests/integration/monitoring-with-team.yaml
This PR fixes some last issues in the team sidecar, netpol and servicemonitor configuration after changing the team monitoring stack schema
> fix: team monitoring stack schema change

- charts/otomi-pipelines/templates/tekton-otomi-git-clone.yaml
- charts/otomi-pipelines/templates/tekton-pipeline.yaml
- src/cmd/apply.ts
This PR aims to solve the following issues:
- team `ArgoCD app` reconfiguration on `otomi.version` upgrade 
- team `ArgoCD  app(s)` reconfiguration on platform app enable
- do not run platform pipeline there are no other changes than in env/teams/
Note: 
- this code change ensures that team `ArgoCD app` is always deployed in platform pipeline.
> feat: enhance otomi pipeline

- charts/team-ns/templates/networkpolicy.yaml
- tests/fixtures/env/teams/services.demo.yaml
- values-schema.yaml
optionally set a custom value for the `otomi.io/app` label. Default is set to the name of the service. This allows to configure netpols when multiple services are used within a workload and all pods have the same `otomi.io/app` label value.
> fix: add netpol podselector

- core.yaml
A fix for this issue in the Loki platform URL:
> fix: loki platform url

- charts/grafana-dashboards/k8s-admin/compute-cluster.json
- charts/grafana-dashboards/k8s-teams/deployment.json
For the team dashboard update for resource utilization, the grafana team deployment dashboard needs to be changed to support `all` for the variable `deployment_name`
For the platform dashboard, the Grafana `Kubernetes / Compute Resources / Cluster` dashboard needs to be changed to provide gauge panels for utilization and request request commitments
> fix: grafana deployment dashboards for Console dashboards

- values/loki/loki.gotmpl
A fix for Loki queryfrontend to do a rolling update to reload the authentication secret whenever there is a change in the teamConfig.
> fix: loki query frontend rolling update on teamConfig change

- charts/team-ns/templates/builds/buildpack.yaml
- tests/fixtures/env/teams/builds.demo.yaml
- values-schema.yaml
To use Gradle in Paketo buildpacks we need to add some additional variables to the pipeline. Note that the values of these variables are now stored as plain text. This will be solved with the introduction of sealed secrets in Otomi.
> fix: add env vars for paketo

- .values/env/settings.yaml
- .values/env/teams.yaml
- helmfile.d/snippets/defaults.yaml
- package-lock.json
- package.json
- src/cmd/migrate.test.ts
- src/cmd/migrate.ts
- tests/fixtures/env/secrets.teams.yaml
- tests/fixtures/env/settings.yaml
- tests/fixtures/env/teams.yaml
- tests/fixtures/env/teams/apps.dev.yaml
- tests/fixtures/env/teams/backups.dev.yaml
- tests/fixtures/env/teams/builds.dev.yaml
- tests/fixtures/env/teams/external-secrets.dev.yaml
- tests/fixtures/env/teams/jobs.dev.yaml
- tests/fixtures/env/teams/services.dev.yaml
- tests/fixtures/env/teams/workloads.dev.yaml
- values-changes.yaml
> feat: migrate values

- .github/workflows/slackbot-release.yml
This PR changes release type from created to published.
Now workflow gets triggered if the release was a draft first
> fix: change created to published

- values/knative/knative-serving-cr.gotmpl
Change ksvc URL template for usingmwildcard certificates that only support a single level of domain name added to the certificate's domain
> fix: ksvc url

- core.yaml
Add path to tekton in core.yaml for adminApps (platform), so link directly shows all the pipelineruns
> fix: tekton platform path

- .github/workflows/integration.yml
This PR fixes te issues with digitalocean workflow not working. It changes the clustername to lowercase and getting the slug version is working again.
[Ticket](https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/gh/redkubes/otomi-core/1471)
> fix: digitalocean release

- charts/gatekeeper-artifacts/templates/_helpers.tpl
- values/argocd-operator/argocd-operator-cr.gotmpl
Gatekeeper mutations do not work with Argo CD operator. This PR excludes the `argocd` namespace from the mutations and configured the Argo CD operator with the `nodePlacement.nodeSelector` when nodeSelector labels are set in Otomi.
```
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
name: set-platform-node-affinity-others
spec:
applyTo:
- groups: [apps]
kinds: [Deployment, ReplicaSet, StatefulSet]
versions: [v1]
- groups: [batch]
kinds: [Job]
versions: [v1]
- groups: [serving.knative.dev]
kinds: [Service]
versions: [v1]
match:
scope: Namespaced
kinds:
- apiGroups: [apps]
kinds: [Deployment, ReplicaSet, StatefulSet]
- apiGroups: [batch]
kinds: [Job]
- apiGroups: [serving.knative.dev]
kinds: [Service]
excludedNamespaces:
- team-admin
- team-demo
- team-dev
- argocd
```
> fix: node selector with argocd

- .github/workflows/integration.yml
- .github/workflows/main.yml
- .github/workflows/scw-remove-clusters-dev-on-schedule.yml
This PR tries to fix the daily cleanup task in scaleway by adding a retry mechanism. It will try up to 5 times with a distance of 1 minute if the deletion command fails either for clusters or private networks. This PR also updates the scw cli to version 2.26.0
> ci: reworked cluster and private network deletion

- .github/workflows/scw-remove-clusters-dev-on-schedule.yml
This MR updated the code of the scheduled github workflow to execute the delete command for each cluster and private network. This way if a single instance can not be deleted it will be skipped and will not block the deletion of other instances.
> ci: fix scheduled deletion of scaleway cluster and private networks

- helmfile.d/snippets/derived.gotmpl
argument change for Linode because of metrics server upgrade
> fix: change extra args metrics-server

- values/velero/velero.gotmpl
This PR will increase the memory limit for the velero-plugin-for-microsoft-azure init container from 32 to 512Mi. While backing up large clusters, the velero server pod gets restarted and we can see the OOMKilled event in k8s events. 
Increasing the memory seems to solve the issue. 
Please check this issue: https://github.com/vmware-tanzu/velero/issues/3234
> feat: updated velero-plugin-for-microsoft-azure memory limit

- values/trivy-operator/trivy-operator.gotmpl
This PR will disable the trivy infra assessment scanner(node-collector job) by default. As experienced in Azure, the node collector job tried to schedule its pods in in the master node(which was not allowed). Since AKS,EKS,GCP are managed kubernetes services, it makes sense to keep this default.
> feat: disabled trivy infra assesment scanner (node-collector job)

- charts/grafana-dashboards/k8s-admin/compute-cluster.json
The platform dashboard in Console uses the Compute Resources / cluster dashboard for showing cluster memory utilization, but the query did not show correct results. This fixes it.
> fix: mem util dashboard

- upgrades/pre/upgrade-2-7-0.sh
This PR fixes the volumesnapshotlocation names in the 2.7 upgrade script to match the one created by otomi installation.
> fix: updated resource names in upgrade script

- charts/velero/Chart.yaml
- charts/velero/README.md
- charts/velero/ci/test-values.yaml
- charts/velero/crds/backups.yaml
- charts/velero/crds/datadownloads.yaml
- charts/velero/crds/datauploads.yaml
- charts/velero/crds/downloadrequests.yaml
- charts/velero/crds/podvolumebackups.yaml
- charts/velero/crds/podvolumerestores.yaml
- charts/velero/crds/restores.yaml
- charts/velero/crds/schedules.yaml
- charts/velero/templates/deployment.yaml
- charts/velero/templates/upgrade-crds/upgrade-crds.yaml
- charts/velero/values.yaml
- upgrades.yaml
- upgrades/pre/upgrade-2-7-0.sh
- upgrades/pre/upgrade-2-8-0.sh
- values/velero/velero.gotmpl
This MR updated velero to version 1.13(current latest).
Tested on Azure AKS cluster:
- Restored backups taken from velero 1.12 ✅
- Created backups for team containing multiple workloads ✅
- Backup/Restored workloads using different storage class backed up PVCs ✅
> feat: update velero to v1.13

- charts/gatekeeper-artifacts/templates/_helpers.tpl
- charts/gatekeeper-artifacts/templates/mutations.yaml
This change ensures that argocd namespace is not included in the `set-team-node-affinity` of `the Assign` resource.
> fix: exclude argocd namespace

- charts/team-ns/templates/builds/buildpack.yaml
- charts/team-ns/templates/tekton-tasks/buildpacks.yaml
The image currently used for buildpacks is outdated and no longer maintained. The underlying GitHub repo has been archived. This causes errors on unsupported features by following common buildpack usage patterns, but also might build images with outdated components.
This PR updates the image to the successor image as found on https://paketo.io/docs/reference/builders-reference/ . It also provides the necessary updates considering the user id during image creation has changed.
> fix: update paketo builder image

- helmfile.d/helmfile-60.teams.yaml
- helmfile.d/snippets/grafana.gotmpl
- values-changes.yaml
- values-schema.yaml
This PR implements the following changes:
- Non-admin users are no longer permitted to log into the platform Grafana instance (which would allow for them to see all logs)
- When team users log into another team's Grafana, they are by default assigned the "Viewer" role (before it was "Editor"). Users are still "Editor" in their own team.
- By setting `teams.[name].managedMonitoring.private` to `true`, only members of that team are allowed to log into this Grafana instance at all. Default is `false` for backwards compatibility.
Depends on redkubes/otomi-api#513
> feat: adjustments to Grafana team permissions

- values-changes.yaml
This PR removes the new field serviceAccount from the value-changes file, as no useful default can be provided, and due to lack of functionality no current installation will currently use Loki together with GCS.
This currently blocks a smooth upgrade from the latest release.
Note there is also redkubes/otomi-api#515, although it is not strictly dependent.
> fix: removed service account from values changes

- helmfile.d/snippets/defaults.yaml
- helmfile.d/snippets/derived.gotmpl
- tests/fixtures/env/apps/metrics-server.yaml
- tests/fixtures/env/cluster.yaml
- values-schema.yaml
- values/metrics-server/metrics-server.gotmpl
The extra args for metrics server are set on multiple levels (defaults, custom app, derived) which resulted in incorrect configuration. This PR fixes this.
> fix: metrics server extra args

- tests/integration/full.yaml
This PR removes the NetworkPolicy from the full integration so now it won't fail anymore.
https://github.com/redkubes/otomi-core/actions/runs/8478776555
> fix: removed networkpolicy

- values/velero/velero.gotmpl
This MR updates the user UID and fsGroup under which the velero node-agent daemonset is running for hardening purposes and avoiding conflict with the gatekeeper runAs policy when enabled.
> fix: added runAsUser parameter for velero's node-agent

- versions.yaml
This PR updates otomi-tasks version to v2.5.0
> feat: updating tasks version

- values/loki/loki.gotmpl
This change prevent loki timeout with query time range above 7 days.
> feat: improve query_limits configuration for loki

- .github/workflows/otomi-tools-build-push.yaml
Script now handles the `v` version prefix and updates correctly.
> fix: handle version prefix in tools version increment script [TOOLS][MAJOR]

- Dockerfile
> chore: bump tools version in otomi core image

- Dockerfile
- tools/Dockerfile
The images `otomi-tools` and `otomi-core` are missing the CA trust store provided by the base image's distribution (Ubuntu). The package is installed but the files are not transferred to the final image. Therefore, contacting any HTTPS site fails unless the verification is deactivated.
This PR adds the `/etc/ssl` directory from the base image, fixing this issue.
> fix: add trusted root certificates to images

- Dockerfile
- src/cmd/apply.ts
- tools/Dockerfile
This PR includes the following changes for making the installation process more robust against temporary connection issues with the Kubernetes API.
* `helm` has been upgraded to the latest release. Since v3.15.0, it has a retry-mechanism to reattempt Kubernetes API requests on certain HTTP status codes or connection timeouts. This is currently hard-coded to 30 retries.
* `helmfile` and the `helm-diff` plugin have been upgraded for ensuring compatibility, while `kubectl` has been upgraded for a closer match to the supported cluster version.
* On initial install, the total amount of queries is reduced by
- skipping validation against the OpenAPI spec of the cluster's Kubernetes API
- bypassing `helm diff` and proceeding to a Helm chart install directly
- running one `helm` instance at a …
> feat: improve robustness of initial install

- charts/otomi-db/templates/cluster.yaml
> fix: wrong indenting in otomi-db chart

- charts/otomi-db/templates/cluster.yaml
- tests/fixtures/env/apps/cnpg.yaml
- tests/fixtures/env/apps/secrets.cnpg.yaml
- tests/fixtures/env/settings.yaml
Enabling backups with s3 configured resulted in the following errors:
```
in helmfile.d/helmfile-04.databases.yaml: command "/opt/homebrew/bin/helm" exited with non-zero status:
PATH:
/opt/homebrew/bin/helm
ARGS:
0: helm (4 bytes)
1: --kube-context (14 bytes)
2: otomi-eks-demo (14 bytes)
3: template (8 bytes)
4: harbor-otomi-db (15 bytes)
5: ../charts/otomi-db (18 bytes)
6: --namespace (11 bytes)
7: harbor (6 bytes)
8: --values (8 bytes)
9: /var/folders/2m/5h7k3bvx20df649hd70d5j400000gq/T/helmfile3969984297/harbor-harbor-otomi-db-values-5594bdc98 (107 bytes)
10: --skip-tests (12 bytes)
ERROR:
exit status 1
EXIT STATUS
1
STDERR:
Error: YAML parse error on otomi-db/templates/cluster.yaml: error converting YAML to JSON: yaml: line 30: mapping values are not allowed in this context
Use …
```
> fix: errors in otomi-db chart

- .values/env/policies.yaml
- tests/fixtures/env/policies.yaml
- values/prometheus-operator/prometheus-operator-team.gotmpl
This PR increases the resource limits of some team resources, as this has frequently caused issues in existing setups (pods OOM killed) with larger amounts of workloads. This should be considered a workaround until we have ways to either inject reasonable estimates or team-specific configuration implemented.
> feat: increase resource limits for prometheus workloads

- .github/workflows/integration.yml
> fix: set linode as default for otomi deploy

- .env.sample
- README.md
- src/cmd/commit.ts
- src/common/envalid.ts
- tests/integration/minimal-with-team.yaml
- tests/integration/monitoring-with-team.yaml
- tests/integration/upgrade.yaml
The `otomi-charts` repo has been transferred to the Linode org and is renamed to `apl-charts`. This PR includes the changes needed to clone the apl-charts instead of the otomi-charts.
> fix: change repo url for catalog charts

- core.yaml
This PR adds `apl-keycloak-operator` namespace.
> fix: add apl-keycloak-operator namespace

- charts/apl-keycloak-operator/templates/deployment.yaml
- charts/apl-keycloak-operator/templates/secrets.yaml
- values/apl-keycloak-operator/apl-keycloak-operator.gotmpl
This PR will apply the following changes:
- extra check for untrustedCa for volumemount and volume on apl-keycloak-operator
- fix for apl-keycloak-operator secrets.yaml, now it doesn't throw a nil error on the tls object
> fix: apl keycloak operator tls

- helmfile.d/snippets/derived.gotmpl
This PR:
- enables minio when obj is configured for `minioLocal`
- removes the `$v.apps.gitea.enabled` logic because Gitea is always enabled
> fix: derived

- charts/team-ns/templates/istio-virtualservices.yaml
This PR fixes the wrong `*` sniHosts when a `CNAME` is used. Using `*` is not supported anymore so we need to set the hosts
> fix: sni hosts

- charts/loki/values.yaml
- values/loki/loki.gotmpl
This PR fixes the broken Loki multi-tenancy. The problem is the setup of the Loki Distributed Helm Chart. Most of the Loki configuration options are combined in just one value `{{ .Values.loki.config }}`. The `auth-enabled` in one of them. In the `loki.config` other Chart values can be used. But not all Loki configuration options are supported in the values.yaml. Using values within values in the values.yaml makes it very difficult to modify values using a .gotmpl.
If any of you has an idea to go around this issue (other than trying to change this in the upstream Grafana helm-charts project), please let me know.
Another option would be (as previously done) provide the full configuration values in the loki.gotmpl. But if we want users to modify config, this would not be the preferred way.
> fix: loki auth for multi-tenancy

- helmfile.d/snippets/defaults.yaml
- values-schema.yaml
- versions.yaml
[APL-137](https://jira.linode.com/browse/APL-137)
> feat: empty rawValues in defaults 

- src/cmd/validate-templates.ts
> fix(apl-146): validate-templates

- charts/otomi-console/values.yaml
- docker-compose.yml
- helmfile.d/snippets/defaults.yaml
- helmfile.d/snippets/job.gotmpl
- values/keycloak-operator/keycloak-operator-cr.gotmpl
- values/otomi-console/otomi-console.gotmpl
- versions.yaml
https://jira.linode.com/browse/APL-135
This PR updates otomi-console files to pull the `apl-console` image from the linode docker hub.
https://hub.docker.com/repository/docker/linode/apl-console/general
Is paired with: https://github.com/linode/apl-console/pull/423
> feat: apl-console linode dockerhub

- charts/apl-gitea-operator/values.yaml
- charts/apl-harbor-operator/values.yaml
- charts/apl-keycloak-operator/values.yaml
- charts/otomi-operator/values.yaml
- charts/wait-for/templates/job.yaml
- charts/wait-for/values.yaml
- helmfile.d/snippets/defaults.yaml
- versions.yaml
https://jira.linode.com/browse/APL-135
This PR updates otomi-tasks files to pull the `apl-tasks` image from the linode docker hub.
https://hub.docker.com/repository/docker/linode/apl-tasks/general
Is paired with: https://github.com/linode/apl-tasks/pull/109
> feat: linode dockerhub apl-tasks

- tests/fixtures/env/secrets.settings.yaml
- tests/fixtures/env/settings.yaml
- values/loki/loki.gotmpl
When OBJ is not configured (or set to disabled), the Loki storageConfig is now configured to use filesystem. This allows to use Loki without OBJ.
> fix: loki storage config without OBJ

- .github/workflows/cloudtty-build-push.yml
- tools/Dockerfile-tty
https://jira.linode.com/browse/APL-135
This PR updates otomi-tty files to push/pull the `apl-tty` image from the linode docker hub.
https://hub.docker.com/repository/docker/linode/apl-tty/general
Is paired with: https://github.com/linode/apl-api/pull/542
> feat: linode dockerhub apl-tty

- helmfile.d/snippets/defaults.yaml
- values/argocd/argocd.gotmpl
This PR fixes: override the default`targetMemoryUtilizationPercentage` to 70 for the server and repo-server HPA
> fix: argocd hpa defaults

- charts/otomi-console/values.yaml
- values/gitea/gitea.gotmpl
- versions.yaml
This PR removes Gitea oauth configuration from the `gitea.gotmpl` file. Gitea oauth configuration will be done by apl-gitea-operator.
Is paired with: https://github.com/linode/apl-tasks/pull/108
> fix: gitea oauth configuration

- .github/ISSUE_TEMPLATE/k8s_support.md
- .github/workflows/integration.yml
- .github/workflows/main.yml
- .github/workflows/otomi-tools-build-push.yaml
- Dockerfile
- bin/common.sh
- binzx/README.md
- binzx/otomi
- chart/apl/templates/job.yaml
- chart/apl/templates/post-job.yaml
- charts/otomi-api/values.yaml
- charts/otomi-pipelines/templates/tekton-otomi-git-clone.yaml
- charts/otomi-pipelines/templates/tekton-otomi-task-teams.yaml
- charts/otomi-pipelines/templates/tekton-otomi-task.yaml
- docker-compose.yml
- helmfile.d/snippets/defaults.yaml
- helmfile.d/snippets/job.gotmpl
- src/cmd/bootstrap.ts
- tools/Readme.md
- values/otomi-api/otomi-api.gotmpl
- values/otomi-console/otomi-console.gotmpl
- versions.yaml
https://jira.linode.com/browse/APL-135
This PR updates the `otomi-core` and `otomi-tools` configurations to ensure that the `apl-core` and `apl-tools` images are pulled from and pushed to the linode dockerhub.
Please note that there is no GitHub workflow set up for the `apl-tools-db` image. As a result, the `apl-tools-db` image has been manually pushed to the new registry.
https://hub.docker.com/repository/docker/linode/apl-core/general
https://hub.docker.com/repository/docker/linode/apl-tools/general
https://hub.docker.com/repository/docker/linode/apl-tools-db/general
Please ensure that all the images mentioned in [this ticket](https://jira.linode.com/browse/APL-135) are pulled from the new registry by following the steps below:
- Use the feature branch from this PR to create a new …
> feat: linode dockerhub apl-core and apl-tools

- helmfile.d/snippets/defaults.yaml
Adjust default resource configuration based on monitoring a long running environment.
> fix: trivy resource defaults

- README.md
Change links to docs because of domain change (from otomi.io to apl-docs.net)
> fix: readme docs link

- .github/workflows/integration.yml
This PR sets the workflow input for k8s version to 1.29.
The previous input was still 1.28 but linode does not support that version anymore when creating new clusters.
Because of this it tried to match 1.28 to one the supported versions, which does not work and results in the workflow failing.
Linode Console
Linode CLI command
Failed Pipeline because the k8s version is empty
> fix: set workflow input to 1.29

- charts/otomi-pipelines/templates/tekton-otomi-git-clone.yaml
Fixes error:
```
gitea-http.gitea.svc.cluster.local:3000/otomi/values.git/
Cloning into 'values'...
warning: templates not found in /usr/share/git-core/templates
fatal: unable to access 'https://gitea-http.gitea.svc.cluster.local:3000/otomi/values.git/': gnutls_handshake() failed: Error in the pull function
```
> fix: clone repo in pipeline

- charts/otomi-db/templates/cluster.yaml
- charts/otomi-db/values.yaml
- helmfile.d/snippets/defaults.yaml
- values/gitea/gitea-otomi-db.gotmpl
- values/harbor/harbor-otomi-db.gotmpl
- values/keycloak/keycloak-otomi-db.gotmpl
- values/prometheus-operator/prometheus-operator.gotmpl
To show all default app values in Console, all defaults are now added to the `defaults/yaml`.
- Templates are validated
- Values are validated
- Templates for all otomi-db's (Gitea, Harbor and Keycloak) have been tested
> fix: set defaults for apps

- src/cmd/apply-as-apps.ts
- values/argocd/argocd.gotmpl
> feat: fix argocd out of sync issues

- values/velero/velero.gotmpl
Set `backupStorageLocation` for both minio and linode to the `defaultBackupStorageLocation`
> fix: velero storage backup location

- helmfile.d/snippets/defaults.yaml
- values/cert-manager-webhook-linode/cert-manager-webhook-linode.gotmpl
- values/tempo/tempo.gotmpl
- Improve default resource requests and limits for cert-manager webhook for linode
- Improve resource limits for Tempo and add defaults for autoscaling
> fix: defaults for linode webhook and tempo app

- helmfile.d/snippets/defaults.yaml
- values-schema.yaml
- values/external-dns/external-dns.gotmpl
- add defaults for external-dns resources
- fix Linode DNS apiToken
> fix: ex dns resources and dns apiToken Linode

- helmfile.d/snippets/defaults.yaml
Increase memory limits for apl-gitea-operator because the operator runs on 80% Limit constantly
> fix: increase mem limits of apl-gitea operator

- helmfile.d/snippets/defaults.yaml
- tests/fixtures/env/apps/ingress-nginx-net-a.yaml
- tests/fixtures/env/apps/ingress-nginx-platform.yaml
- tests/fixtures/env/apps/ingress-nginx.yaml
- values-changes.yaml
- values-schema.yaml
- values/gitea/gitea.gotmpl
- values/harbor/harbor.gotmpl
- values/ingress-nginx/ingress-nginx.gotmpl
- values/jaeger-operator/jaeger-operator.gotmpl
- values/loki/loki.gotmpl
- values/otomi-api/otomi-api.gotmpl
- values/otomi-console/otomi-console.gotmpl
- values/prometheus-operator/prometheus-operator.gotmpl
- values/promtail/promtail.gotmpl
This PR:
- configures resource defaults for a number of apps. Design principle is NOT to specify resources in any `.gotmpl`, but instead define them in the `otomi-values` and add the defaults to the `defaults.yaml`
- optimizes resources.request for a number of apps to prevent `CPUThrottlingHigh` alerts
> fix: default resource config

- .github/workflows/integration.yml
This PR fixes the `integration.yml` file `determine exact k8s version` step in order to create a cluster.
Linode currently supports versions 1.31, 1.30, and 1.29. When we try to create a cluster with version 1.30, the integration.yml file interprets it as 1.3 due to YAML truncation. This leads to filtering using startsWith(1.3), which captures the two version numbers (--k8s_version "1.31" "1.30") instead of 1.30, causing the linode-cli command/error below.
command: ` linode-cli lke cluster-create \
--label <cluster-label> \
--region nl-ams \
--k8s_version "1.31" "1.30" \
--control_plane.high_availability true \
--node_pools.type g6-dedicated-8 --node_pools.count 3 \
--node_pools.autoscaler.enabled true \
--node_pools.autoscaler.max 3 \
--node_pools.autoscaler.min 3 \
--tags testing \ …
> fix: determine exact k8s version step

- values/knative/knative-serving-cr.gotmpl
Fix for APL-238. The KnativeServing CR needed updating after upgrade.
> fix: knative domain-template

- chart/apl/templates/_helpers.tpl
- chart/apl/templates/job.yaml
- chart/apl/templates/post-job.yaml
- chart/apl/templates/rbac.yaml
- chart/apl/templates/serviceaccount.yaml
- chart/apl/templates/sops-secrets.yaml
- chart/apl/templates/values-secrets.yaml
This PR updates the helm _helpers.tpl to use apl instead of otomi for fullname, labels and selectorLabels values generation.
> fix: updated helm apl chart

- charts/prometheus-msteams/templates/deployment.yaml
This PR fixes a duplicate key in the Deployment of `prometheus-msteams`.
> fix: remove duplicate imagePullPolicy

- values/istio-operator/istio-operator.gotmpl
Istio version `1.22.1` broke the serviceentries used for the egress filtering. These changes have been reverted in the `1.22.5` patch release.
> fix: upgrade istio to 1.22.5

- helmfile.d/snippets/derived.gotmpl
This PR fixes a bug that slipped through while refactoring the certificate secret names with different providers. As a workaround, the certificate can currently be copied into the new name during the installation process.
> fix: byo certificate name

- helmfile.d/helmfile-60.teams.yaml
- values-changes.yaml
- values-schema.yaml
This PR drops the per-team setting `managedMonitoring.private`, which was mainly intended to maintain backwards compatibility to the behavior before the multitenancy became the default, despite being potentially confusing.
> feat: remove optional private grafana

- helmfile.d/snippets/defaults.yaml
- values-schema.yaml
- values/argocd/argocd.gotmpl
During testing with 66 applications, the controller had insufficient memory and got status `OOMKilled`. This PR increases the memory limits for the ArgoCD controller and adds queue processors to the schema for optimization when using more applications. The queue processors are set back to the ArgoCD defaults.
> fix: queue processors and controller resource defaults

- chart/otomi/values.schema.json
- tests/fixtures/env/settings.yaml
- values-changes.yaml
- values-schema.yaml
> fix: remove additional cluster logic

- helmfile.d/snippets/defaults.yaml
- values/oauth2-proxy/oauth2-proxy-raw.gotmpl
This PR adds CORS related annotations to the oauth2-proxy ingress so that it can be queried from cloud manager.
> feat: added cors for ouath2-proxy ingress

- charts/grafana-dashboards/trivy-teams/trivy-teams.json
The trivy Team dashboard in Grafana needs to use the default datasource in case Thanos is enabled.
> fix: set datasource for trivy dashboard to default

- README.md
- src/cmd/commit.ts
Remove "Application Platform" as an accepted variation of the product name
> fix: naming

- CHANGELOG.md
- package-lock.json
- package.json
- versions.yaml
> chore(release): 4.1.0

- .github/workflows/integration.yml
This PR is part of the new cluster clean-up logic. Instead of deleting clusters with the delete_me_tonight tag, it will delete all the clusters except the ones having the do_not_delete tag.
Related PR: https://bits.linode.com/APL/apl-gh-actions/pull/4
> feat: removed uneeded tag

- charts/otomi-db/templates/cluster.yaml
- values/gitea/gitea-otomi-db.gotmpl
- values/harbor/harbor-otomi-db.gotmpl
- values/keycloak/keycloak-otomi-db.gotmpl
This PR fixes the "backup size growing indefinitely" issue.
This PR updates the endpointUrl for the object storages where the backups and WAL files are saved.
Fixing this result in a successful backup and also a successful enforcement of the retention policy.
In this PR we are also enabling the WAL and Data compression to make the backup smaller.
Tested on a new cluster by setting the retention policy to 1 day.
> feat: APL-372 updated cnpg endpointurl

- .github/workflows/cloudtty-build-push.yml
- .github/workflows/otomi-tools-build-push.yaml
This PR fixes the apl-tools patch image generation.
For the time being a change of files named `*tools/Dockerfile*` would trigger a build of the apl-tools image.
This PR fixes it so that only changes in `tools/Dockerfile` (the Dockerfile for apl-tools) trigger the build and push.
> feat: fixed apl-tools patch image generation

- .github/dependabot.yml
- .github/workflows/main.yml
- .github/workflows/otomi-tools-build-push.yaml
- Dockerfile
- tools/Dockerfile
- This PR accommodates the [dependabot initiated PR](https://github.com/linode/apl-core/pull/1825/commits/eca8eed349da786be824b2970535be40a9504ec0) and adds small fixes in the docker build job which otherwise causes an error in the pipeline run like showed here:
See: https://stackoverflow.com/questions/72049008/docker-build-push-action-not-a-valid-object-name-outputs-all-branches-and-tag
- Additionally upgrading this github action adds a [build summary](https://docs.docker.com/build/ci/github-actions/build-summary/)
- It also updated the Dockerfile instructions to capital letters as per convention.
> fix: github-actions update

- helmfile.d/snippets/derived.gotmpl
Install minio app only when minio is enabled as this is the default workflow for enabling apps.
> fix: install minio based on enabled

- chart/chart-index/Chart.yaml
Removed external-secrets from chart-index since we are not using the chart anymore.
See pipeline error: https://github.com/linode/apl-core/actions/runs/12287670240/job/34290108929#step:7:49
> fix: removed external-secrets charts from chart-index

- ci/src/update-helm-chart-deps.mjs
I noticed that some PRs created by Helm chart bot have more that one dependency version number updated in the Chart.yaml file. Example: https://github.com/linode/apl-core/pull/1863/files#diff-1c892db7344feb10640b6353e7452859ca22f33e57737e167a4cc55d23ba91f2
This PR fixes that issue.
Testing:
In local environment: at ci/.env:
```
CI_UPDATE_TYPE='minor'
CI_HELM_CHART_NAME_FILTER='[]'
CI_GH_CREATE_PR='false'
CI_GIT_BASELINE_BRANCH='APL-11-1'
CI_GIT_LOCAL_BRANCH_ONLY='true'
```
then run
```
src/update-helm-chart-deps.mjs
```
then 
```
git checkout ci-update-sealed-secrets-to-2.17.0
```
```
gd HEAD~1
```
You should see only one version updated
```
dependencies:
- name: argo-cd
version: 6.7.3
@@ -60,7 +44,7 @@ dependencies:
version: 6.11.2
repository: https://grafana.github.io/helm-charts
- …
```
> ci: update chart version index for a single chart

- src/cmd/apply.ts
- src/common/k8s.ts
This code change:
- ensures setting correct current working directory 
- increases waitTillGitRepoAvailable timeout to accommodate DNS and Certificate request delays
- fixes the `Retrying in undefined ms` log message
- improve readability of error message once performing `git ls-remote` command
Testing methodology:
- I was able to reproduce the issue by deploying the following the `APL-449-reproduce` branch (https://github.com/linode/apl-core/pull/1884)
- I tested the change by deploying the `APL-449-test branch`, which exactly the same as this PR except I lowered down the  retries parameter.
> fix: ensure rootDir and increase retry timeout

- src/common/k8s.ts
Removed `repoUrl` from `waitTillGitRepoAvailable` error message otherwise it will expose the admin password in the installer logs as showed here:
> fix: removed repoUrl variable from error message

- values/team-ns/team-ns.gotmpl
This PR fixes the reference to team networking policies in the team-ns chart.
> fix: reference to team network policies

- versions.yaml
This PR updates tasks to 3.6.1
> chore: update task version to 3.6.1

- values/gitea/gitea.gotmpl
> feat: increase Gitea timeout

- versions.yaml
This PR updates Api to 3.6.0 and console to 3.5.1
> chore: update console and api to latest release

- src/common/values.ts
- values-schema.yaml
Reverts linode/apl-core#1910
While we do want this change, it has turned out that the Gitea credentials change and restart during the pipeline run blocks a clean migration. It works on a fresh installation, but will never commit the change back to the values repo in a branch change and therefore cause excessive pipeline run times each time.
We should merge this change again, once we have found a solution for this.
> revert: fix - unique admin password for gitea

- .github/workflows/integration.yml
This PR updates the list of versions to the ones currently shown as supported by the Linode API, including 1.32 and removing 1.29. Also a change was made to wait until the Kubeconfig can be retrieved, as relying on all nodes being up and running turned out not to be sufficient.
> ci: update workflow to support k8s 1.32 and wait for kubeconfig

- charts/team-ns/templates/argocd/argocd-applicationset.yaml
Fix to solve argo sync issues when using team-admin to create a workload using a chart with a validatingwebhookconfig resource.
> fix: workload with validatingwebhookcfg

- chart/chart-index/Chart.yaml
- ci/src/update-helm-chart-deps.mjs
This PR includes the following changes to the chart update script:
* It checks if the index version corresponds with the chart's version. If not, the update is skipped. When running locally, `CI_GIT_LOCAL_BRANCH_ONLY` can be set to `true` for preparing a fix. Resulting changes should be submitted to a separate PR.
* Any errors leading to skipping a chart are summarized at the end, as they tend to disappear in the log output.
* Some improvements to running the script locally. For example, the checkout hooks are skipped.
Also, two inaccuracies in the chart index were found and fixed, including the version mismatches above and a missing alias for the `tekton-pipeline` chart.
> ci: update chart index and improve checks

- versions.yaml
> chore: versions

- tests/integration/minimal-with-team.yaml
- tests/integration/monitoring-with-team.yaml
This PR fixes the path of workload values in the installation profiles.
> ci: path of workload values in installation profiles

- versions.yaml
> chore: set api version 4.1.1

- src/cmd/commit.ts
> fix: pull before pushing to gitea in commitAndPush func

- .github/workflows/create_rc.yml
- .github/workflows/patch_rc.yml
- ci/scripts/create_rc.sh
- ci/scripts/create_rc_tag.sh
- ci/scripts/prepare_chart_for_release.sh
This PR adds 2 new github worflows:
- a manually triggered one to create release candidates
- an automatically triggered one that patches the RC when a fix is added
A short summary of what the Release Candidate GitHub workflow does:
1. Takes input for a commit SHA(optional) and a dry_run flag(default=true).
2. Checks out the code and installs dependencies (standard-version).
3. Determines the commit to base the release candidate (RC) on.
4. Calculates a new version (without tagging or committing) using standard-version.
5. Creates an RC branch, and if not a dry run, makes a prerelease and pushes it.
6. Creates a GitHub release (skipped in dry run).
7. Checks out the new RC branch in a second job.
8. Updates Helm chart files with the new app version.
9. Appends README content and generates …
> ci: added release candidate pipelines

- .github/workflows/pr-auto-updater.yml
This PR updated the "PR Auto Updater" workflow to use a PAT instead of the default GITHIB_TOKEN since this one [can not trigger a workflow](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow). 
We need this workflow to trigger an image build in the affected branch after that branch is automatically updated with the lates changes on main.
For more context:
- https://github.com/orgs/community/discussions/25702
- https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow
> ci: updated workflow to use a PAT instead of the default GITHUB_TOKEN

- .github/workflows/create_rc.yml
- .github/workflows/patch_rc.yml
Fixing the order when we configure git identity. the `npm release` command needs an identity becuse it needs to create a branch and tag this the git configuration must happen before.
> ci: fixed git config order

- .github/workflows/patch_rc.yml
- package.json
This PR updates the token used by the "Patch Release Candidate" pipeline so that after it patches a RC, it also triggers the build pipeline. Currently commits pushed with the GITHUB_TOKEN [do not trigger a pipeline run](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow).
> ci: updated github token to bot token

- charts/apl-gitea-operator/templates/rbac.yaml
- charts/team-ns/templates/rbac.yaml
This PR moves roles and rolebindings required by the Gitea operator to the chart that deploys the application. Before this change, these resources were deployed along with every team. That causes a lot of unsuccessful connection attempts during the APL installation, before the first team (admin) is rolled out. After the first team, the roles are redundant with every new team.
While the effect might not be noticeable in a running cluster, this is likely to improve stability during install, since the load of Kubernetes API requests can trigger rate limiting.
The apl-gitea-operator should not show any "Forbidden" error messages.
> fix: move operator rbac to chart

- charts/team-ns/templates/limitrange.yaml
Tekton init containers does not specify resources thus resource quota is blocking it.
> fix: set resource limits to enforce resource defaults for containers

- charts/team-ns/templates/limitrange.yaml
- values/team-ns/team-ns.gotmpl
This change ensures that ingress for team apps is always created regardless of app being enabled or not.
> fix: always deploy ingress for team core apps 

- charts/team-ns/templates/limitrange.yaml
- helmfile.d/snippets/defaults.gotmpl
The ResourceQuota and LimitRange limits are not yet compatible with the whole platform, thus for time being we need to remove them.
Once ResourceQuota  limit is set then every pod is required to have them defined. We initially assumed that by defining LimitRange solves that issue. That turned out to be a wrong assumption because some Pod are OOM killed due to the default low memory limits.
> fix: remove resourcequota and limitrange limits

- values/loki/auth-config.gotmpl
After wrapping team settings under the settings property we did not anticipate changes required for Loki.
That issue was not caught because the templating logic had a fallback to 'XXX' value.
> fix: team access to loki logs

- CHANGELOG.md
- package-lock.json
- package.json
- versions.yaml
This PR releases version v4.5.0.
The changelog can be found [here](https://github.com/linode/apl-core/blob/release_v4.5.0/CHANGELOG.md).
> chore(release): 4.5.0

- versions.yaml
This PR sets the versions of other components back to `main`, as prior to the release.
This is the common development setup and does not require specific testing.
N/A
> chore: set versions to main

- .github/workflows/integration.yml
set default version to k8s v1.32 as v1.33 is not supported on linode yet
> fix: set default k8s version 1.32

- src/common/crypt.ts
- src/common/utils.test.ts
- src/common/utils.ts
This PR changes the way that we check for differences between the dec and encrypted files. Because of the session stack the time difference was too small to actually see if there was a difference or not.
> fix: actually check for difference between files

- ci/scripts/trigger_dev.sh
Since the  https://github.com/linode/apl-core/pull/2151 the gitea-credentials secret is not in the otomi-pipelines namespace.
n/a
> ci: read gitea-credentials from cluster

- ci/scripts/trigger_dev.sh
Since we replaced the Tekton pipeline with the APL operator, we no longer need to push fake-commits for triggering an upgrade. However, since the branch never changes, the APL operator needs to become aware of the upstream changes. This PR changes the script to restart the pods.
> ci: restart dev apl-operator after main branch update

- values/gitea/gitea.gotmpl
Reconfigure Gitea to use single-instance Redis for reducing memory usage.
> fix: use single-instance cache for Gitea

- .github/workflows/integration.yml
> fix: set default k8s version to 1.33 for gh workflows

- charts/otomi-db/templates/cluster.yaml
- helmfile.d/snippets/defaults.yaml
- values-schema.yaml
- values/gitea/gitea-otomi-db.gotmpl
- values/harbor/harbor-otomi-db.gotmpl
- values/keycloak/keycloak-otomi-db.gotmpl
This fixes the critical issue of CloudnativePG backups failing to upload to Linode Object Storage, eventually resulting in full volumes.
> fix: barman compatibility with non-aws object storage

- src/cmd/migrate.ts
This PR fixes an issue caused by changes in the Kubernetes API client, returning a different structure of the response. Without it, it fails to install APL operator and leaves the platform in a broken state.
> fix: status code evaluation from k8s client

- src/cmd/upgrade.test.ts
- src/cmd/upgrade.ts
- src/common/utils.test.ts
- src/common/utils.ts
This PR fixes the version filter that checks for relevant upgrade scripts based on the platform version number (i.e. regardless of the values, which are handled by migrations). It also replaces a custom version check with the `semver` library. This makes version syntax more strict, but easier to discover errors.
An existing test was altered. An upgrade from version `2.1.1-rc.1` should include upgrades for `2.1.1`, but not `2.1.0`.
> fix: prerelease versions in upgrade check

- src/cmd/apply.ts
- src/common/k8s.test.ts
- src/common/k8s.ts
- restart otomi-api after installation is finished.
> feat: implement restart functionality for otomi-api deployment

- core.yaml
By removing the `app: tekton` label we instruct APL to always deploy those namespaces.
For the sake of consistency we also ensure that `apl-operator` is deployed in the same way
> fix: always deploy tekton and apl related namespaces

- chart/chart-index/Chart.yaml
The chart reference for OAuth2-Proxy is not set to the source we are actually using. Therefore, we are not getting any automated upgrades. Neither would the upgrades work correctly, since the referenced chart has a different structure.
> ci: oauth2-proxy chart source

- src/cmd/apply-as-apps.ts
- src/cmd/apply.ts
- src/common/envalid.ts
This PR adds two features to the `otomi apply` command:
* There are two environment variables, `APPS_REPO_URL` and `APPS_REVISION`, which allow configuring the `repoURL` and `targetRevision` of ArgoCD application manifests when using `otomi apply-as-apps` or `otomi apply --tekton`. This way, feature branches can be pushed to other locations than the public GitHub repo for experimental purposes.
* `otomi apply --tekton` supports selectors, e.g. by file or name, for selectively configuring the ArgoCD applications.
These two come in useful when testing a new version of an app, without pushing all incremental changes to GitHub. Also, using the selectors, it does not keep re-enabling `apl-operator`, reverting any potential changes sent from a local Otomi CLI. Application upgrades can be tested …
> feat: set custom repository and use selectors on argocd applications

- index.yaml
cleaning up the following entries:
- https://github.com/linode/apl-core/releases/download/otomi-0.5.9/otomi-0.5.9.tgz
- https://github.com/linode/apl-core/releases/download/otomi-0.5.10/otomi-0.5.10.tgz
- https://github.com/linode/apl-core/releases/download/otomi-0.5.50/otomi-0.5.50.tgz
- https://github.com/linode/apl-core/releases/download/apl-3.0.0-rc.1/apl-3.0.0-rc.1.tgz
> fix: cleaning up missing charts

- values/knative-serving/knative-serving-cr.gotmpl
This PR fixes a typo in the `net-istio-controller/webhook` image override in the knativeserving CR. See examples: https://knative.dev/docs/install/operator/configuring-serving-cr/#download-images-individually-without-secrets
> fix: net-istio-webhook image override

- helmfile.d/snippets/defaults.yaml
- tests/fixtures/env/settings/versions.yaml
- values-changes.yaml
We decided to not migrate current clusters to use ORCS automatically but let the user do so if needed through the values repository by changing the `useORCS` flag in the `otomi.yaml` file.
> feat: reverting ORCS migration for upgraded clusters

- helmfile.d/snippets/derived.gotmpl
This provider allows enabling ORCS only when the cluster.provider is linode. Otherwise the useORCS flag will have no effect.
> feat: making linode provider an ORCS dependency

- src/cmd/commit.ts
- src/cmd/gen-drone.ts
- src/common/debug.ts
- src/common/zx-enhance.ts
- src/operator/k8s.ts
- src/test-init.ts
apl-core also commits to Gitea. This can cause for merge conflicts in the apl-operator when changes are really fast after each other.
The way we handle it now is that we will just reset the commit apl-core made and let it resolve in the next apply loop. So if there are conflicts it will reset the commit and not push anything. The reconciliation loop wil add the next commit
> fix: handle merge conflicts in apl-operator

- src/cmd/commit.ts
This PR fixes to push apl-charts repository with tag.
Ticket: https://jira.linode.com/browse/APL-1067
- Create a cluster using the APL-1076 branch.
- After the first login, navigate to the Catalog page.
- Verify that all the default Helm charts are present from the Gitea charts repository.
- Verify that both the main branch and the main tag exist in the Gitea charts repository.
> fix: push apl-charts repository with tag
